# ================================
# PINOVARA - Docker Compose Override
# ================================
# Configurações específicas para desenvolvimento local
# Este arquivo é automaticamente mesclado com docker-compose.yml

version: '3.8'

services:
  # ========== BACKEND (Desenvolvimento) ==========
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - NODE_ENV=development
      - VITE_API_LOGGING=true
    volumes:
      # Montar código fonte para hot-reload
      - ./backend/src:/app/src:ro
      - ./backend/prisma:/app/prisma:ro
      # Montar node_modules do host para evitar conflitos
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # ========== BANCO REMOTO (Desenvolvimento) ==========
  # Continua usando DATABASE_URL do ambiente (banco remoto)

  # ========== FRONTEND (Desenvolvimento) ==========
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pinovara-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - /app/node_modules
    networks:
      - pinovara-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # ========== NGINX (Desenvolvimento - Desabilitado) ==========
  nginx:
    profiles:
      - production  # Só executa em produção

  # ========== REDIS (Desenvolvimento) ==========
  redis:
    ports:
      - "6380:6379"  # Porta diferente para desenvolvimento
