
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.1
 * Query Engine version: 272a37d34178c2894197e17273bf937f25acdeac
 */
Prisma.prismaVersion = {
  client: "6.17.1",
  engine: "272a37d34178c2894197e17273bf937f25acdeac"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Audit_logsScalarFieldEnum = {
  id: 'id',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  oldData: 'oldData',
  newData: 'newData',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.Db_connectionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  host: 'host',
  port: 'port',
  database: 'database',
  username: 'username',
  password: 'password',
  description: 'description',
  active: 'active',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ModulesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizacaoScalarFieldEnum = {
  id: 'id',
  inicio: 'inicio',
  fim: 'fim',
  deviceid: 'deviceid',
  data_visita: 'data_visita',
  estado: 'estado',
  municipio: 'municipio',
  gps_lat: 'gps_lat',
  gps_lng: 'gps_lng',
  gps_alt: 'gps_alt',
  gps_acc: 'gps_acc',
  nome: 'nome',
  cnpj: 'cnpj',
  telefone: 'telefone',
  email: 'email',
  data_fundacao: 'data_fundacao',
  organizacao_end_logradouro: 'organizacao_end_logradouro',
  organizacao_end_bairro: 'organizacao_end_bairro',
  organizacao_end_complemento: 'organizacao_end_complemento',
  organizacao_end_numero: 'organizacao_end_numero',
  organizacao_end_cep: 'organizacao_end_cep',
  representante_nome: 'representante_nome',
  representante_cpf: 'representante_cpf',
  representante_rg: 'representante_rg',
  representante_telefone: 'representante_telefone',
  representante_email: 'representante_email',
  representante_end_logradouro: 'representante_end_logradouro',
  representante_end_bairro: 'representante_end_bairro',
  representante_end_complemento: 'representante_end_complemento',
  representante_end_numero: 'representante_end_numero',
  representante_end_cep: 'representante_end_cep',
  representante_funcao: 'representante_funcao',
  caracteristicas_n_total_socios: 'caracteristicas_n_total_socios',
  caracteristicas_n_total_socios_caf: 'caracteristicas_n_total_socios_caf',
  caracteristicas_n_distintos_caf: 'caracteristicas_n_distintos_caf',
  caracteristicas_n_socios_paa: 'caracteristicas_n_socios_paa',
  caracteristicas_n_naosocios_paa: 'caracteristicas_n_naosocios_paa',
  caracteristicas_n_socios_pnae: 'caracteristicas_n_socios_pnae',
  caracteristicas_n_naosocios_pnae: 'caracteristicas_n_naosocios_pnae',
  caracteristicas_n_ativos_total: 'caracteristicas_n_ativos_total',
  caracteristicas_n_ativos_caf: 'caracteristicas_n_ativos_caf',
  caracteristicas_n_naosocio_op_total: 'caracteristicas_n_naosocio_op_total',
  caracteristicas_n_naosocio_op_caf: 'caracteristicas_n_naosocio_op_caf',
  caracteristicas_ta_a_mulher: 'caracteristicas_ta_a_mulher',
  caracteristicas_ta_a_homem: 'caracteristicas_ta_a_homem',
  caracteristicas_ta_e_mulher: 'caracteristicas_ta_e_mulher',
  caracteristicas_ta_e_homem: 'caracteristicas_ta_e_homem',
  caracteristicas_ta_o_mulher: 'caracteristicas_ta_o_mulher',
  caracteristicas_ta_o_homem: 'caracteristicas_ta_o_homem',
  caracteristicas_ta_i_mulher: 'caracteristicas_ta_i_mulher',
  caracteristicas_ta_i_homem: 'caracteristicas_ta_i_homem',
  caracteristicas_ta_p_mulher: 'caracteristicas_ta_p_mulher',
  caracteristicas_ta_p_homem: 'caracteristicas_ta_p_homem',
  caracteristicas_ta_af_mulher: 'caracteristicas_ta_af_mulher',
  caracteristicas_ta_af_homem: 'caracteristicas_ta_af_homem',
  caracteristicas_ta_q_mulher: 'caracteristicas_ta_q_mulher',
  caracteristicas_ta_q_homem: 'caracteristicas_ta_q_homem',
  caracteristicas_ta_caf_convencional: 'caracteristicas_ta_caf_convencional',
  caracteristicas_ta_caf_agroecologico: 'caracteristicas_ta_caf_agroecologico',
  caracteristicas_ta_caf_transicao: 'caracteristicas_ta_caf_transicao',
  caracteristicas_ta_caf_organico: 'caracteristicas_ta_caf_organico',
  go_organizacao_7_resposta: 'go_organizacao_7_resposta',
  go_organizacao_7_comentario: 'go_organizacao_7_comentario',
  go_organizacao_7_proposta: 'go_organizacao_7_proposta',
  go_organizacao_8_resposta: 'go_organizacao_8_resposta',
  go_organizacao_8_comentario: 'go_organizacao_8_comentario',
  go_organizacao_8_proposta: 'go_organizacao_8_proposta',
  go_organizacao_9_resposta: 'go_organizacao_9_resposta',
  go_organizacao_9_comentario: 'go_organizacao_9_comentario',
  go_organizacao_9_proposta: 'go_organizacao_9_proposta',
  go_organizacao_10_resposta: 'go_organizacao_10_resposta',
  go_organizacao_10_comentario: 'go_organizacao_10_comentario',
  go_organizacao_10_proposta: 'go_organizacao_10_proposta',
  go_organizacao_11_resposta: 'go_organizacao_11_resposta',
  go_organizacao_11_comentario: 'go_organizacao_11_comentario',
  go_organizacao_11_proposta: 'go_organizacao_11_proposta',
  go_organizacao_12_resposta: 'go_organizacao_12_resposta',
  go_organizacao_12_comentario: 'go_organizacao_12_comentario',
  go_organizacao_12_proposta: 'go_organizacao_12_proposta',
  go_organizacao_13_resposta: 'go_organizacao_13_resposta',
  go_organizacao_13_comentario: 'go_organizacao_13_comentario',
  go_organizacao_13_proposta: 'go_organizacao_13_proposta',
  go_direcao_14_resposta: 'go_direcao_14_resposta',
  go_direcao_14_comentario: 'go_direcao_14_comentario',
  go_direcao_14_proposta: 'go_direcao_14_proposta',
  go_direcao_15_resposta: 'go_direcao_15_resposta',
  go_direcao_15_comentario: 'go_direcao_15_comentario',
  go_direcao_15_proposta: 'go_direcao_15_proposta',
  go_direcao_16_resposta: 'go_direcao_16_resposta',
  go_direcao_16_comentario: 'go_direcao_16_comentario',
  go_direcao_16_proposta: 'go_direcao_16_proposta',
  go_direcao_17_resposta: 'go_direcao_17_resposta',
  go_direcao_17_comentario: 'go_direcao_17_comentario',
  go_direcao_17_proposta: 'go_direcao_17_proposta',
  go_direcao_18_resposta: 'go_direcao_18_resposta',
  go_direcao_18_comentario: 'go_direcao_18_comentario',
  go_direcao_18_proposta: 'go_direcao_18_proposta',
  go_direcao_19_resposta: 'go_direcao_19_resposta',
  go_direcao_19_comentario: 'go_direcao_19_comentario',
  go_direcao_19_proposta: 'go_direcao_19_proposta',
  go_direcao_20_resposta: 'go_direcao_20_resposta',
  go_direcao_20_comentario: 'go_direcao_20_comentario',
  go_direcao_20_proposta: 'go_direcao_20_proposta',
  go_direcao_21_resposta: 'go_direcao_21_resposta',
  go_direcao_21_comentario: 'go_direcao_21_comentario',
  go_direcao_21_proposta: 'go_direcao_21_proposta',
  go_controle_20_resposta: 'go_controle_20_resposta',
  go_controle_20_comentario: 'go_controle_20_comentario',
  go_controle_20_proposta: 'go_controle_20_proposta',
  go_controle_21_resposta: 'go_controle_21_resposta',
  go_controle_21_comentario: 'go_controle_21_comentario',
  go_controle_21_proposta: 'go_controle_21_proposta',
  go_controle_22_resposta: 'go_controle_22_resposta',
  go_controle_22_comentario: 'go_controle_22_comentario',
  go_controle_22_proposta: 'go_controle_22_proposta',
  go_controle_23_resposta: 'go_controle_23_resposta',
  go_controle_23_comentario: 'go_controle_23_comentario',
  go_controle_23_proposta: 'go_controle_23_proposta',
  go_controle_24_resposta: 'go_controle_24_resposta',
  go_controle_24_comentario: 'go_controle_24_comentario',
  go_controle_24_proposta: 'go_controle_24_proposta',
  go_controle_25_resposta: 'go_controle_25_resposta',
  go_controle_25_comentario: 'go_controle_25_comentario',
  go_controle_25_proposta: 'go_controle_25_proposta',
  go_controle_26_resposta: 'go_controle_26_resposta',
  go_controle_26_comentario: 'go_controle_26_comentario',
  go_controle_26_proposta: 'go_controle_26_proposta',
  go_controle_27_resposta: 'go_controle_27_resposta',
  go_controle_27_comentario: 'go_controle_27_comentario',
  go_controle_27_proposta: 'go_controle_27_proposta',
  go_educacao_26_resposta: 'go_educacao_26_resposta',
  go_educacao_26_comentario: 'go_educacao_26_comentario',
  go_educacao_26_proposta: 'go_educacao_26_proposta',
  go_educacao_27_resposta: 'go_educacao_27_resposta',
  go_educacao_27_comentario: 'go_educacao_27_comentario',
  go_educacao_27_proposta: 'go_educacao_27_proposta',
  go_educacao_28_resposta: 'go_educacao_28_resposta',
  go_educacao_28_comentario: 'go_educacao_28_comentario',
  go_educacao_28_proposta: 'go_educacao_28_proposta',
  go_educacao_29_resposta: 'go_educacao_29_resposta',
  go_educacao_29_comentario: 'go_educacao_29_comentario',
  go_educacao_29_proposta: 'go_educacao_29_proposta',
  go_educacao_30_resposta: 'go_educacao_30_resposta',
  go_educacao_30_comentario: 'go_educacao_30_comentario',
  go_educacao_30_proposta: 'go_educacao_30_proposta',
  go_estrategia_5_resposta: 'go_estrategia_5_resposta',
  go_estrategia_5_comentario: 'go_estrategia_5_comentario',
  go_estrategia_5_proposta: 'go_estrategia_5_proposta',
  go_estrategia_6_resposta: 'go_estrategia_6_resposta',
  go_estrategia_6_comentario: 'go_estrategia_6_comentario',
  go_estrategia_6_proposta: 'go_estrategia_6_proposta',
  go_estrutura_1_resposta: 'go_estrutura_1_resposta',
  go_estrutura_1_comentario: 'go_estrutura_1_comentario',
  go_estrutura_1_proposta: 'go_estrutura_1_proposta',
  go_estrutura_2_resposta: 'go_estrutura_2_resposta',
  go_estrutura_2_comentario: 'go_estrutura_2_comentario',
  go_estrutura_2_proposta: 'go_estrutura_2_proposta',
  go_estrutura_3_resposta: 'go_estrutura_3_resposta',
  go_estrutura_3_comentario: 'go_estrutura_3_comentario',
  go_estrutura_3_proposta: 'go_estrutura_3_proposta',
  go_estrutura_4_resposta: 'go_estrutura_4_resposta',
  go_estrutura_4_comentario: 'go_estrutura_4_comentario',
  go_estrutura_4_proposta: 'go_estrutura_4_proposta',
  gpp_planejamento_4_resposta: 'gpp_planejamento_4_resposta',
  gpp_planejamento_4_comentario: 'gpp_planejamento_4_comentario',
  gpp_planejamento_4_proposta: 'gpp_planejamento_4_proposta',
  gpp_planejamento_5_resposta: 'gpp_planejamento_5_resposta',
  gpp_planejamento_5_comentario: 'gpp_planejamento_5_comentario',
  gpp_planejamento_5_proposta: 'gpp_planejamento_5_proposta',
  gpp_planejamento_6_resposta: 'gpp_planejamento_6_resposta',
  gpp_planejamento_6_comentario: 'gpp_planejamento_6_comentario',
  gpp_planejamento_6_proposta: 'gpp_planejamento_6_proposta',
  gpp_logistica_7_resposta: 'gpp_logistica_7_resposta',
  gpp_logistica_7_comentario: 'gpp_logistica_7_comentario',
  gpp_logistica_7_proposta: 'gpp_logistica_7_proposta',
  gpp_logistica_8_resposta: 'gpp_logistica_8_resposta',
  gpp_logistica_8_comentario: 'gpp_logistica_8_comentario',
  gpp_logistica_8_proposta: 'gpp_logistica_8_proposta',
  gpp_logistica_9_resposta: 'gpp_logistica_9_resposta',
  gpp_logistica_9_comentario: 'gpp_logistica_9_comentario',
  gpp_logistica_9_proposta: 'gpp_logistica_9_proposta',
  gpp_logistica_10_resposta: 'gpp_logistica_10_resposta',
  gpp_logistica_10_comentario: 'gpp_logistica_10_comentario',
  gpp_logistica_10_proposta: 'gpp_logistica_10_proposta',
  gpp_logistica_11_resposta: 'gpp_logistica_11_resposta',
  gpp_logistica_11_comentario: 'gpp_logistica_11_comentario',
  gpp_logistica_11_proposta: 'gpp_logistica_11_proposta',
  gpp_logistica_12_resposta: 'gpp_logistica_12_resposta',
  gpp_logistica_12_comentario: 'gpp_logistica_12_comentario',
  gpp_logistica_12_proposta: 'gpp_logistica_12_proposta',
  gpp_valor_13_resposta: 'gpp_valor_13_resposta',
  gpp_valor_13_comentario: 'gpp_valor_13_comentario',
  gpp_valor_13_proposta: 'gpp_valor_13_proposta',
  gpp_valor_14_resposta: 'gpp_valor_14_resposta',
  gpp_valor_14_comentario: 'gpp_valor_14_comentario',
  gpp_valor_14_proposta: 'gpp_valor_14_proposta',
  gpp_valor_15_resposta: 'gpp_valor_15_resposta',
  gpp_valor_15_comentario: 'gpp_valor_15_comentario',
  gpp_valor_15_proposta: 'gpp_valor_15_proposta',
  gpp_fluxo_16_resposta: 'gpp_fluxo_16_resposta',
  gpp_fluxo_16_comentario: 'gpp_fluxo_16_comentario',
  gpp_fluxo_16_proposta: 'gpp_fluxo_16_proposta',
  gpp_fluxo_17_resposta: 'gpp_fluxo_17_resposta',
  gpp_fluxo_17_comentario: 'gpp_fluxo_17_comentario',
  gpp_fluxo_17_proposta: 'gpp_fluxo_17_proposta',
  gpp_fluxo_18_resposta: 'gpp_fluxo_18_resposta',
  gpp_fluxo_18_comentario: 'gpp_fluxo_18_comentario',
  gpp_fluxo_18_proposta: 'gpp_fluxo_18_proposta',
  gpp_fluxo_19_resposta: 'gpp_fluxo_19_resposta',
  gpp_fluxo_19_comentario: 'gpp_fluxo_19_comentario',
  gpp_fluxo_19_proposta: 'gpp_fluxo_19_proposta',
  gpp_fluxo_20_resposta: 'gpp_fluxo_20_resposta',
  gpp_fluxo_20_comentario: 'gpp_fluxo_20_comentario',
  gpp_fluxo_20_proposta: 'gpp_fluxo_20_proposta',
  gpp_fluxo_21_resposta: 'gpp_fluxo_21_resposta',
  gpp_fluxo_21_comentario: 'gpp_fluxo_21_comentario',
  gpp_fluxo_21_proposta: 'gpp_fluxo_21_proposta',
  gpp_fluxo_22_resposta: 'gpp_fluxo_22_resposta',
  gpp_fluxo_22_comentario: 'gpp_fluxo_22_comentario',
  gpp_fluxo_22_proposta: 'gpp_fluxo_22_proposta',
  gpp_qualidade_23_resposta: 'gpp_qualidade_23_resposta',
  gpp_qualidade_23_comentario: 'gpp_qualidade_23_comentario',
  gpp_qualidade_23_proposta: 'gpp_qualidade_23_proposta',
  gpp_qualidade_24_resposta: 'gpp_qualidade_24_resposta',
  gpp_qualidade_24_comentario: 'gpp_qualidade_24_comentario',
  gpp_qualidade_24_proposta: 'gpp_qualidade_24_proposta',
  gpp_qualidade_25_resposta: 'gpp_qualidade_25_resposta',
  gpp_qualidade_25_comentario: 'gpp_qualidade_25_comentario',
  gpp_qualidade_25_proposta: 'gpp_qualidade_25_proposta',
  gpp_qualidade_26_resposta: 'gpp_qualidade_26_resposta',
  gpp_qualidade_26_comentario: 'gpp_qualidade_26_comentario',
  gpp_qualidade_26_proposta: 'gpp_qualidade_26_proposta',
  gpp_qualidade_27_resposta: 'gpp_qualidade_27_resposta',
  gpp_qualidade_27_comentario: 'gpp_qualidade_27_comentario',
  gpp_qualidade_27_proposta: 'gpp_qualidade_27_proposta',
  gpp_qualidade_28_resposta: 'gpp_qualidade_28_resposta',
  gpp_qualidade_28_comentario: 'gpp_qualidade_28_comentario',
  gpp_qualidade_28_proposta: 'gpp_qualidade_28_proposta',
  gpp_producao_29_resposta: 'gpp_producao_29_resposta',
  gpp_producao_29_comentario: 'gpp_producao_29_comentario',
  gpp_producao_29_proposta: 'gpp_producao_29_proposta',
  gpp_reg_sanitaria_1_resposta: 'gpp_reg_sanitaria_1_resposta',
  gpp_reg_sanitaria_1_comentario: 'gpp_reg_sanitaria_1_comentario',
  gpp_reg_sanitaria_1_proposta: 'gpp_reg_sanitaria_1_proposta',
  gpp_reg_sanitaria_2_resposta: 'gpp_reg_sanitaria_2_resposta',
  gpp_reg_sanitaria_2_comentario: 'gpp_reg_sanitaria_2_comentario',
  gpp_reg_sanitaria_2_proposta: 'gpp_reg_sanitaria_2_proposta',
  gpp_reg_sanitaria_3_resposta: 'gpp_reg_sanitaria_3_resposta',
  gpp_reg_sanitaria_3_comentario: 'gpp_reg_sanitaria_3_comentario',
  gpp_reg_sanitaria_3_proposta: 'gpp_reg_sanitaria_3_proposta',
  gc_e_comercial_1_resposta: 'gc_e_comercial_1_resposta',
  gc_e_comercial_1_comentario: 'gc_e_comercial_1_comentario',
  gc_e_comercial_1_proposta: 'gc_e_comercial_1_proposta',
  gc_e_comercial_2_resposta: 'gc_e_comercial_2_resposta',
  gc_e_comercial_2_comentario: 'gc_e_comercial_2_comentario',
  gc_e_comercial_2_proposta: 'gc_e_comercial_2_proposta',
  gc_e_comercial_3_resposta: 'gc_e_comercial_3_resposta',
  gc_e_comercial_3_comentario: 'gc_e_comercial_3_comentario',
  gc_e_comercial_3_proposta: 'gc_e_comercial_3_proposta',
  gc_e_comercial_4_resposta: 'gc_e_comercial_4_resposta',
  gc_e_comercial_4_comentario: 'gc_e_comercial_4_comentario',
  gc_e_comercial_4_proposta: 'gc_e_comercial_4_proposta',
  gc_e_comercial_5_resposta: 'gc_e_comercial_5_resposta',
  gc_e_comercial_5_comentario: 'gc_e_comercial_5_comentario',
  gc_e_comercial_5_proposta: 'gc_e_comercial_5_proposta',
  gc_e_comercial_6_resposta: 'gc_e_comercial_6_resposta',
  gc_e_comercial_6_comentario: 'gc_e_comercial_6_comentario',
  gc_e_comercial_6_proposta: 'gc_e_comercial_6_proposta',
  gc_e_comercial_7_resposta: 'gc_e_comercial_7_resposta',
  gc_e_comercial_7_comentario: 'gc_e_comercial_7_comentario',
  gc_e_comercial_7_proposta: 'gc_e_comercial_7_proposta',
  gc_e_comercial_8_resposta: 'gc_e_comercial_8_resposta',
  gc_e_comercial_8_comentario: 'gc_e_comercial_8_comentario',
  gc_e_comercial_8_proposta: 'gc_e_comercial_8_proposta',
  gc_e_comercial_9_resposta: 'gc_e_comercial_9_resposta',
  gc_e_comercial_9_comentario: 'gc_e_comercial_9_comentario',
  gc_e_comercial_9_proposta: 'gc_e_comercial_9_proposta',
  gc_mercado_10_resposta: 'gc_mercado_10_resposta',
  gc_mercado_10_comentario: 'gc_mercado_10_comentario',
  gc_mercado_10_proposta: 'gc_mercado_10_proposta',
  gc_mercado_11_resposta: 'gc_mercado_11_resposta',
  gc_mercado_11_comentario: 'gc_mercado_11_comentario',
  gc_mercado_11_proposta: 'gc_mercado_11_proposta',
  gc_mercado_12_resposta: 'gc_mercado_12_resposta',
  gc_mercado_12_comentario: 'gc_mercado_12_comentario',
  gc_mercado_12_proposta: 'gc_mercado_12_proposta',
  gc_mercado_13_resposta: 'gc_mercado_13_resposta',
  gc_mercado_13_comentario: 'gc_mercado_13_comentario',
  gc_mercado_13_proposta: 'gc_mercado_13_proposta',
  gc_mercado_14_resposta: 'gc_mercado_14_resposta',
  gc_mercado_14_comentario: 'gc_mercado_14_comentario',
  gc_mercado_14_proposta: 'gc_mercado_14_proposta',
  gc_mercado_15_resposta: 'gc_mercado_15_resposta',
  gc_mercado_15_comentario: 'gc_mercado_15_comentario',
  gc_mercado_15_proposta: 'gc_mercado_15_proposta',
  gc_comercial_15_resposta: 'gc_comercial_15_resposta',
  gc_comercial_15_comentario: 'gc_comercial_15_comentario',
  gc_comercial_15_proposta: 'gc_comercial_15_proposta',
  gc_comercial_16_resposta: 'gc_comercial_16_resposta',
  gc_comercial_16_comentario: 'gc_comercial_16_comentario',
  gc_comercial_16_proposta: 'gc_comercial_16_proposta',
  gc_comercial_17_resposta: 'gc_comercial_17_resposta',
  gc_comercial_17_comentario: 'gc_comercial_17_comentario',
  gc_comercial_17_proposta: 'gc_comercial_17_proposta',
  gc_comercial_18_resposta: 'gc_comercial_18_resposta',
  gc_comercial_18_comentario: 'gc_comercial_18_comentario',
  gc_comercial_18_proposta: 'gc_comercial_18_proposta',
  gc_comercial_19_resposta: 'gc_comercial_19_resposta',
  gc_comercial_19_comentario: 'gc_comercial_19_comentario',
  gc_comercial_19_proposta: 'gc_comercial_19_proposta',
  gc_comercial_20_resposta: 'gc_comercial_20_resposta',
  gc_comercial_20_comentario: 'gc_comercial_20_comentario',
  gc_comercial_20_proposta: 'gc_comercial_20_proposta',
  gc_comercial_21_resposta: 'gc_comercial_21_resposta',
  gc_comercial_21_comentario: 'gc_comercial_21_comentario',
  gc_comercial_21_proposta: 'gc_comercial_21_proposta',
  gc_modelo_21_resposta: 'gc_modelo_21_resposta',
  gc_modelo_21_comentario: 'gc_modelo_21_comentario',
  gc_modelo_21_proposta: 'gc_modelo_21_proposta',
  gc_modelo_22_resposta: 'gc_modelo_22_resposta',
  gc_modelo_22_comentario: 'gc_modelo_22_comentario',
  gc_modelo_22_proposta: 'gc_modelo_22_proposta',
  gc_modelo_23_resposta: 'gc_modelo_23_resposta',
  gc_modelo_23_comentario: 'gc_modelo_23_comentario',
  gc_modelo_23_proposta: 'gc_modelo_23_proposta',
  gc_modelo_24_resposta: 'gc_modelo_24_resposta',
  gc_modelo_24_comentario: 'gc_modelo_24_comentario',
  gc_modelo_24_proposta: 'gc_modelo_24_proposta',
  gc_modelo_25_resposta: 'gc_modelo_25_resposta',
  gc_modelo_25_comentario: 'gc_modelo_25_comentario',
  gc_modelo_25_proposta: 'gc_modelo_25_proposta',
  gc_modelo_26_resposta: 'gc_modelo_26_resposta',
  gc_modelo_26_comentario: 'gc_modelo_26_comentario',
  gc_modelo_26_proposta: 'gc_modelo_26_proposta',
  gc_modelo_27_resposta: 'gc_modelo_27_resposta',
  gc_modelo_27_comentario: 'gc_modelo_27_comentario',
  gc_modelo_27_proposta: 'gc_modelo_27_proposta',
  gc_modelo_28_resposta: 'gc_modelo_28_resposta',
  gc_modelo_28_comentario: 'gc_modelo_28_comentario',
  gc_modelo_28_proposta: 'gc_modelo_28_proposta',
  gf_contas_5_resposta: 'gf_contas_5_resposta',
  gf_contas_5_comentario: 'gf_contas_5_comentario',
  gf_contas_5_proposta: 'gf_contas_5_proposta',
  gf_contas_6_resposta: 'gf_contas_6_resposta',
  gf_contas_6_comentario: 'gf_contas_6_comentario',
  gf_contas_6_proposta: 'gf_contas_6_proposta',
  gf_contas_7_resposta: 'gf_contas_7_resposta',
  gf_contas_7_comentario: 'gf_contas_7_comentario',
  gf_contas_7_proposta: 'gf_contas_7_proposta',
  gf_contas_8_resposta: 'gf_contas_8_resposta',
  gf_contas_8_comentario: 'gf_contas_8_comentario',
  gf_contas_8_proposta: 'gf_contas_8_proposta',
  gf_contas_9_resposta: 'gf_contas_9_resposta',
  gf_contas_9_comentario: 'gf_contas_9_comentario',
  gf_contas_9_proposta: 'gf_contas_9_proposta',
  gf_contas_10_resposta: 'gf_contas_10_resposta',
  gf_contas_10_comentario: 'gf_contas_10_comentario',
  gf_contas_10_proposta: 'gf_contas_10_proposta',
  gf_contas_11_resposta: 'gf_contas_11_resposta',
  gf_contas_11_comentario: 'gf_contas_11_comentario',
  gf_contas_11_proposta: 'gf_contas_11_proposta',
  gf_contas_12_resposta: 'gf_contas_12_resposta',
  gf_contas_12_comentario: 'gf_contas_12_comentario',
  gf_contas_12_proposta: 'gf_contas_12_proposta',
  gf_contas_13_resposta: 'gf_contas_13_resposta',
  gf_contas_13_comentario: 'gf_contas_13_comentario',
  gf_caixa_14_resposta: 'gf_caixa_14_resposta',
  gf_caixa_14_comentario: 'gf_caixa_14_comentario',
  gf_caixa_14_proposta: 'gf_caixa_14_proposta',
  gf_caixa_15_resposta: 'gf_caixa_15_resposta',
  gf_caixa_15_comentario: 'gf_caixa_15_comentario',
  gf_caixa_15_proposta: 'gf_caixa_15_proposta',
  gf_caixa_16_resposta: 'gf_caixa_16_resposta',
  gf_caixa_16_comentario: 'gf_caixa_16_comentario',
  gf_caixa_16_proposta: 'gf_caixa_16_proposta',
  gf_estoque_17_resposta: 'gf_estoque_17_resposta',
  gf_estoque_17_comentario: 'gf_estoque_17_comentario',
  gf_estoque_17_proposta: 'gf_estoque_17_proposta',
  gf_estoque_18_resposta: 'gf_estoque_18_resposta',
  gf_estoque_18_comentario: 'gf_estoque_18_comentario',
  gf_estoque_18_proposta: 'gf_estoque_18_proposta',
  gf_estoque_19_resposta: 'gf_estoque_19_resposta',
  gf_estoque_19_comentario: 'gf_estoque_19_comentario',
  gf_estoque_19_proposta: 'gf_estoque_19_proposta',
  gf_resultado_20_resposta: 'gf_resultado_20_resposta',
  gf_resultado_20_comentario: 'gf_resultado_20_comentario',
  gf_resultado_20_proposta: 'gf_resultado_20_proposta',
  gf_resultado_21_resposta: 'gf_resultado_21_resposta',
  gf_resultado_21_comentario: 'gf_resultado_21_comentario',
  gf_resultado_21_proposta: 'gf_resultado_21_proposta',
  gf_analise_22_resposta: 'gf_analise_22_resposta',
  gf_analise_22_comentario: 'gf_analise_22_comentario',
  gf_analise_22_proposta: 'gf_analise_22_proposta',
  gf_analise_23_resposta: 'gf_analise_23_resposta',
  gf_analise_23_comentario: 'gf_analise_23_comentario',
  gf_analise_23_proposta: 'gf_analise_23_proposta',
  gf_analise_24_resposta: 'gf_analise_24_resposta',
  gf_analise_24_comentario: 'gf_analise_24_comentario',
  gf_analise_24_proposta: 'gf_analise_24_proposta',
  gf_fiscal_25_resposta: 'gf_fiscal_25_resposta',
  gf_fiscal_25_comentario: 'gf_fiscal_25_comentario',
  gf_fiscal_25_proposta: 'gf_fiscal_25_proposta',
  gf_fiscal_26_resposta: 'gf_fiscal_26_resposta',
  gf_fiscal_26_comentario: 'gf_fiscal_26_comentario',
  gf_fiscal_26_proposta: 'gf_fiscal_26_proposta',
  gf_balanco_1_resposta: 'gf_balanco_1_resposta',
  gf_balanco_1_comentario: 'gf_balanco_1_comentario',
  gf_balanco_1_proposta: 'gf_balanco_1_proposta',
  gf_balanco_2_resposta: 'gf_balanco_2_resposta',
  gf_balanco_2_comentario: 'gf_balanco_2_comentario',
  gf_balanco_2_proposta: 'gf_balanco_2_proposta',
  gf_balanco_3_resposta: 'gf_balanco_3_resposta',
  gf_balanco_3_comentario: 'gf_balanco_3_comentario',
  gf_balanco_3_proposta: 'gf_balanco_3_proposta',
  gf_balanco_4_resposta: 'gf_balanco_4_resposta',
  gf_balanco_4_comentario: 'gf_balanco_4_comentario',
  gf_balanco_4_proposta: 'gf_balanco_4_proposta',
  gp_p_organizacao_1_resposta: 'gp_p_organizacao_1_resposta',
  gp_p_organizacao_1_comentario: 'gp_p_organizacao_1_comentario',
  gp_p_organizacao_1_proposta: 'gp_p_organizacao_1_proposta',
  gp_p_organizacao_2_resposta: 'gp_p_organizacao_2_resposta',
  gp_p_organizacao_2_comentario: 'gp_p_organizacao_2_comentario',
  gp_p_organizacao_2_proposta: 'gp_p_organizacao_2_proposta',
  gp_p_organizacao_3_resposta: 'gp_p_organizacao_3_resposta',
  gp_p_organizacao_3_comentario: 'gp_p_organizacao_3_comentario',
  gp_p_organizacao_3_proposta: 'gp_p_organizacao_3_proposta',
  gp_p_organizacao_4_resposta: 'gp_p_organizacao_4_resposta',
  gp_p_organizacao_4_comentario: 'gp_p_organizacao_4_comentario',
  gp_p_organizacao_4_proposta: 'gp_p_organizacao_4_proposta',
  gp_p_organizacao_5_resposta: 'gp_p_organizacao_5_resposta',
  gp_p_organizacao_5_comentario: 'gp_p_organizacao_5_comentario',
  gp_p_organizacao_5_proposta: 'gp_p_organizacao_5_proposta',
  gp_p_organizacao_6_resposta: 'gp_p_organizacao_6_resposta',
  gp_p_organizacao_6_comentario: 'gp_p_organizacao_6_comentario',
  gp_p_organizacao_6_proposta: 'gp_p_organizacao_6_proposta',
  gp_p_organizacao_7_resposta: 'gp_p_organizacao_7_resposta',
  gp_p_organizacao_7_comentario: 'gp_p_organizacao_7_comentario',
  gp_p_organizacao_7_proposta: 'gp_p_organizacao_7_proposta',
  gp_p_organizacao_8_resposta: 'gp_p_organizacao_8_resposta',
  gp_p_organizacao_8_comentario: 'gp_p_organizacao_8_comentario',
  gp_p_organizacao_8_proposta: 'gp_p_organizacao_8_proposta',
  gp_p_organizacao_9_resposta: 'gp_p_organizacao_9_resposta',
  gp_p_organizacao_9_comentario: 'gp_p_organizacao_9_comentario',
  gp_p_organizacao_9_proposta: 'gp_p_organizacao_9_proposta',
  gp_p_desenvolvimento_10_resposta: 'gp_p_desenvolvimento_10_resposta',
  gp_p_desenvolvimento_10_comentario: 'gp_p_desenvolvimento_10_comentario',
  gp_p_desenvolvimento_10_proposta: 'gp_p_desenvolvimento_10_proposta',
  gp_p_desenvolvimento_11_resposta: 'gp_p_desenvolvimento_11_resposta',
  gp_p_desenvolvimento_11_comentario: 'gp_p_desenvolvimento_11_comentario',
  gp_p_desenvolvimento_11_proposta: 'gp_p_desenvolvimento_11_proposta',
  gp_p_desenvolvimento_12_resposta: 'gp_p_desenvolvimento_12_resposta',
  gp_p_desenvolvimento_12_comentario: 'gp_p_desenvolvimento_12_comentario',
  gp_p_desenvolvimento_12_proposta: 'gp_p_desenvolvimento_12_proposta',
  gp_p_desenvolvimento_13_resposta: 'gp_p_desenvolvimento_13_resposta',
  gp_p_desenvolvimento_13_comentario: 'gp_p_desenvolvimento_13_comentario',
  gp_p_desenvolvimento_13_proposta: 'gp_p_desenvolvimento_13_proposta',
  gp_trabalho_14_resposta: 'gp_trabalho_14_resposta',
  gp_trabalho_14_comentario: 'gp_trabalho_14_comentario',
  gp_trabalho_14_proposta: 'gp_trabalho_14_proposta',
  gp_trabalho_15_resposta: 'gp_trabalho_15_resposta',
  gp_trabalho_15_comentario: 'gp_trabalho_15_comentario',
  gp_trabalho_15_proposta: 'gp_trabalho_15_proposta',
  gp_trabalho_16_resposta: 'gp_trabalho_16_resposta',
  gp_trabalho_16_comentario: 'gp_trabalho_16_comentario',
  gp_trabalho_16_proposta: 'gp_trabalho_16_proposta',
  gp_trabalho_17_resposta: 'gp_trabalho_17_resposta',
  gp_trabalho_17_comentario: 'gp_trabalho_17_comentario',
  gp_trabalho_17_proposta: 'gp_trabalho_17_proposta',
  gp_geracao_18_resposta: 'gp_geracao_18_resposta',
  gp_geracao_18_comentario: 'gp_geracao_18_comentario',
  gp_geracao_18_proposta: 'gp_geracao_18_proposta',
  gp_geracao_19_resposta: 'gp_geracao_19_resposta',
  gp_geracao_19_comentario: 'gp_geracao_19_comentario',
  gp_geracao_19_proposta: 'gp_geracao_19_proposta',
  gp_geracao_20_resposta: 'gp_geracao_20_resposta',
  gp_geracao_20_comentario: 'gp_geracao_20_comentario',
  gp_geracao_20_proposta: 'gp_geracao_20_proposta',
  gs_socioambiental_1_resposta: 'gs_socioambiental_1_resposta',
  gs_socioambiental_1_comentario: 'gs_socioambiental_1_comentario',
  gs_socioambiental_1_proposta: 'gs_socioambiental_1_proposta',
  gs_socioambiental_2_resposta: 'gs_socioambiental_2_resposta',
  gs_socioambiental_2_comentario: 'gs_socioambiental_2_comentario',
  gs_socioambiental_2_proposta: 'gs_socioambiental_2_proposta',
  gs_socioambiental_3_resposta: 'gs_socioambiental_3_resposta',
  gs_socioambiental_3_comentario: 'gs_socioambiental_3_comentario',
  gs_socioambiental_3_proposta: 'gs_socioambiental_3_proposta',
  gs_socioambiental_4_resposta: 'gs_socioambiental_4_resposta',
  gs_socioambiental_4_comentario: 'gs_socioambiental_4_comentario',
  gs_socioambiental_4_proposta: 'gs_socioambiental_4_proposta',
  gs_socioambiental_5_resposta: 'gs_socioambiental_5_resposta',
  gs_socioambiental_5_comentario: 'gs_socioambiental_5_comentario',
  gs_socioambiental_5_proposta: 'gs_socioambiental_5_proposta',
  gs_ambiental_6_resposta: 'gs_ambiental_6_resposta',
  gs_ambiental_6_comentario: 'gs_ambiental_6_comentario',
  gs_ambiental_6_proposta: 'gs_ambiental_6_proposta',
  gs_ambiental_7_resposta: 'gs_ambiental_7_resposta',
  gs_ambiental_7_comentario: 'gs_ambiental_7_comentario',
  gs_ambiental_7_proposta: 'gs_ambiental_7_proposta',
  gs_ambiental_8_resposta: 'gs_ambiental_8_resposta',
  gs_ambiental_8_comentario: 'gs_ambiental_8_comentario',
  gs_ambiental_8_proposta: 'gs_ambiental_8_proposta',
  gs_ambiental_9_resposta: 'gs_ambiental_9_resposta',
  gs_ambiental_9_comentario: 'gs_ambiental_9_comentario',
  gs_ambiental_9_proposta: 'gs_ambiental_9_proposta',
  gs_reg_ambiental_10_resposta: 'gs_reg_ambiental_10_resposta',
  gs_reg_ambiental_10_comentario: 'gs_reg_ambiental_10_comentario',
  gs_reg_ambiental_10_proposta: 'gs_reg_ambiental_10_proposta',
  gs_reg_ambiental_11_resposta: 'gs_reg_ambiental_11_resposta',
  gs_reg_ambiental_11_comentario: 'gs_reg_ambiental_11_comentario',
  gs_reg_ambiental_11_proposta: 'gs_reg_ambiental_11_proposta',
  gs_reg_ambiental_12_resposta: 'gs_reg_ambiental_12_resposta',
  gs_reg_ambiental_12_comentario: 'gs_reg_ambiental_12_comentario',
  gs_reg_ambiental_12_proposta: 'gs_reg_ambiental_12_proposta',
  gs_reg_ambiental_13_resposta: 'gs_reg_ambiental_13_resposta',
  gs_reg_ambiental_13_comentario: 'gs_reg_ambiental_13_comentario',
  gs_reg_ambiental_13_proposta: 'gs_reg_ambiental_13_proposta',
  gs_reg_ambiental_14_resposta: 'gs_reg_ambiental_14_resposta',
  gs_reg_ambiental_14_comentario: 'gs_reg_ambiental_14_comentario',
  gs_reg_ambiental_14_proposta: 'gs_reg_ambiental_14_proposta',
  gs_impactos_ambiental_15_resposta: 'gs_impactos_ambiental_15_resposta',
  gs_impactos_ambiental_15_comentario: 'gs_impactos_ambiental_15_comentario',
  gs_impactos_ambiental_15_proposta: 'gs_impactos_ambiental_15_proposta',
  gs_impactos_ambiental_16_resposta: 'gs_impactos_ambiental_16_resposta',
  gs_impactos_ambiental_16_comentario: 'gs_impactos_ambiental_16_comentario',
  gs_impactos_ambiental_16_proposta: 'gs_impactos_ambiental_16_proposta',
  gs_impactos_ambiental_17_resposta: 'gs_impactos_ambiental_17_resposta',
  gs_impactos_ambiental_17_comentario: 'gs_impactos_ambiental_17_comentario',
  gs_impactos_ambiental_17_proposta: 'gs_impactos_ambiental_17_proposta',
  gs_impactos_ambiental_18_resposta: 'gs_impactos_ambiental_18_resposta',
  gs_impactos_ambiental_18_comentario: 'gs_impactos_ambiental_18_comentario',
  gs_impactos_ambiental_18_proposta: 'gs_impactos_ambiental_18_proposta',
  gs_impactos_ambiental_19_resposta: 'gs_impactos_ambiental_19_resposta',
  gs_impactos_ambiental_19_comentario: 'gs_impactos_ambiental_19_comentario',
  gs_impactos_ambiental_19_proposta: 'gs_impactos_ambiental_19_proposta',
  gs_impactos_ambiental_20_resposta: 'gs_impactos_ambiental_20_resposta',
  gs_impactos_ambiental_20_comentario: 'gs_impactos_ambiental_20_comentario',
  gs_impactos_ambiental_20_proposta: 'gs_impactos_ambiental_20_proposta',
  gs_impactos_ambiental_21_resposta: 'gs_impactos_ambiental_21_resposta',
  gs_impactos_ambiental_21_comentario: 'gs_impactos_ambiental_21_comentario',
  gs_impactos_ambiental_21_proposta: 'gs_impactos_ambiental_21_proposta',
  gs_impactos_ambiental_22_resposta: 'gs_impactos_ambiental_22_resposta',
  gs_impactos_ambiental_22_comentario: 'gs_impactos_ambiental_22_comentario',
  gs_impactos_ambiental_22_proposta: 'gs_impactos_ambiental_22_proposta',
  gi_iic_1_resposta: 'gi_iic_1_resposta',
  gi_iic_1_comentario: 'gi_iic_1_comentario',
  gi_iic_1_proposta: 'gi_iic_1_proposta',
  gi_iic_2_resposta: 'gi_iic_2_resposta',
  gi_iic_2_comentario: 'gi_iic_2_comentario',
  gi_iic_2_proposta: 'gi_iic_2_proposta',
  gi_iic_3_resposta: 'gi_iic_3_resposta',
  gi_iic_3_comentario: 'gi_iic_3_comentario',
  gi_iic_3_proposta: 'gi_iic_3_proposta',
  gi_iic_4_resposta: 'gi_iic_4_resposta',
  gi_iic_4_comentario: 'gi_iic_4_comentario',
  gi_iic_4_proposta: 'gi_iic_4_proposta',
  gi_iic_5_resposta: 'gi_iic_5_resposta',
  gi_iic_5_comentario: 'gi_iic_5_comentario',
  gi_iic_5_proposta: 'gi_iic_5_proposta',
  gi_mar_6_resposta: 'gi_mar_6_resposta',
  gi_mar_6_comentario: 'gi_mar_6_comentario',
  gi_mar_6_proposta: 'gi_mar_6_proposta',
  gi_mar_7_resposta: 'gi_mar_7_resposta',
  gi_mar_7_comentario: 'gi_mar_7_comentario',
  gi_mar_7_proposta: 'gi_mar_7_proposta',
  gi_mar_8_resposta: 'gi_mar_8_resposta',
  gi_mar_8_comentario: 'gi_mar_8_comentario',
  gi_mar_8_proposta: 'gi_mar_8_proposta',
  gi_mar_9_resposta: 'gi_mar_9_resposta',
  gi_mar_9_comentario: 'gi_mar_9_comentario',
  gi_mar_9_proposta: 'gi_mar_9_proposta',
  gi_time_10_resposta: 'gi_time_10_resposta',
  gi_time_10_comentario: 'gi_time_10_comentario',
  gi_time_10_proposta: 'gi_time_10_proposta',
  gi_time_11_resposta: 'gi_time_11_resposta',
  gi_time_11_comentario: 'gi_time_11_comentario',
  gi_time_11_proposta: 'gi_time_11_proposta',
  gi_time_12_resposta: 'gi_time_12_resposta',
  gi_time_12_comentario: 'gi_time_12_comentario',
  gi_time_12_proposta: 'gi_time_12_proposta',
  gi_time_13_resposta: 'gi_time_13_resposta',
  gi_time_13_comentario: 'gi_time_13_comentario',
  gi_time_13_proposta: 'gi_time_13_proposta',
  gi_time_14_resposta: 'gi_time_14_resposta',
  gi_time_14_comentario: 'gi_time_14_comentario',
  gi_time_14_proposta: 'gi_time_14_proposta',
  is_recursos_naturais_5_resposta: 'is_recursos_naturais_5_resposta',
  is_recursos_naturais_5_comentario: 'is_recursos_naturais_5_comentario',
  is_recursos_naturais_5_proposta: 'is_recursos_naturais_5_proposta',
  is_recursos_naturais_6_resposta: 'is_recursos_naturais_6_resposta',
  is_recursos_naturais_6_comentario: 'is_recursos_naturais_6_comentario',
  is_recursos_naturais_6_proposta: 'is_recursos_naturais_6_proposta',
  is_recursos_naturais_7_resposta: 'is_recursos_naturais_7_resposta',
  is_recursos_naturais_7_comentario: 'is_recursos_naturais_7_comentario',
  is_recursos_naturais_7_proposta: 'is_recursos_naturais_7_proposta',
  is_recursos_naturais_8_resposta: 'is_recursos_naturais_8_resposta',
  is_recursos_naturais_8_comentario: 'is_recursos_naturais_8_comentario',
  is_recursos_naturais_8_proposta: 'is_recursos_naturais_8_proposta',
  is_agua_9_resposta: 'is_agua_9_resposta',
  is_agua_9_comentario: 'is_agua_9_comentario',
  is_agua_9_proposta: 'is_agua_9_proposta',
  is_agua_10_resposta: 'is_agua_10_resposta',
  is_agua_10_comentario: 'is_agua_10_comentario',
  is_agua_10_proposta: 'is_agua_10_proposta',
  is_conforto_ambiental_11_resposta: 'is_conforto_ambiental_11_resposta',
  is_conforto_ambiental_11_comentario: 'is_conforto_ambiental_11_comentario',
  is_conforto_ambiental_11_proposta: 'is_conforto_ambiental_11_proposta',
  is_conforto_ambiental_12_resposta: 'is_conforto_ambiental_12_resposta',
  is_conforto_ambiental_12_comentario: 'is_conforto_ambiental_12_comentario',
  is_conforto_ambiental_12_proposta: 'is_conforto_ambiental_12_proposta',
  is_conforto_ambiental_13_resposta: 'is_conforto_ambiental_13_resposta',
  is_conforto_ambiental_13_comentario: 'is_conforto_ambiental_13_comentario',
  is_conforto_ambiental_13_proposta: 'is_conforto_ambiental_13_proposta',
  is_conforto_ambiental_14_resposta: 'is_conforto_ambiental_14_resposta',
  is_conforto_ambiental_14_comentario: 'is_conforto_ambiental_14_comentario',
  is_conforto_ambiental_14_proposta: 'is_conforto_ambiental_14_proposta',
  is_residuos_15_resposta: 'is_residuos_15_resposta',
  is_residuos_15_comentario: 'is_residuos_15_comentario',
  is_residuos_15_proposta: 'is_residuos_15_proposta',
  is_residuos_16_resposta: 'is_residuos_16_resposta',
  is_residuos_16_comentario: 'is_residuos_16_comentario',
  is_residuos_16_proposta: 'is_residuos_16_proposta',
  is_residuos_17_resposta: 'is_residuos_17_resposta',
  is_residuos_17_comentario: 'is_residuos_17_comentario',
  is_residuos_17_proposta: 'is_residuos_17_proposta',
  is_residuos_18_resposta: 'is_residuos_18_resposta',
  is_residuos_18_comentario: 'is_residuos_18_comentario',
  is_residuos_18_proposta: 'is_residuos_18_proposta',
  is_eficiencia_energetica_1_resposta: 'is_eficiencia_energetica_1_resposta',
  is_eficiencia_energetica_1_comentario: 'is_eficiencia_energetica_1_comentario',
  is_eficiencia_energetica_1_proposta: 'is_eficiencia_energetica_1_proposta',
  is_eficiencia_energetica_2_resposta: 'is_eficiencia_energetica_2_resposta',
  is_eficiencia_energetica_2_comentario: 'is_eficiencia_energetica_2_comentario',
  is_eficiencia_energetica_2_proposta: 'is_eficiencia_energetica_2_proposta',
  is_eficiencia_energetica_3_resposta: 'is_eficiencia_energetica_3_resposta',
  is_eficiencia_energetica_3_comentario: 'is_eficiencia_energetica_3_comentario',
  is_eficiencia_energetica_3_proposta: 'is_eficiencia_energetica_3_proposta',
  is_eficiencia_energetica_4_resposta: 'is_eficiencia_energetica_4_resposta',
  is_eficiencia_energetica_4_comentario: 'is_eficiencia_energetica_4_comentario',
  is_eficiencia_energetica_4_proposta: 'is_eficiencia_energetica_4_proposta',
  meta_instance_id: 'meta_instance_id',
  meta_instance_name: 'meta_instance_name',
  removido: 'removido',
  id_tecnico: 'id_tecnico',
  caracteristicas_n_ingressaram_total_12_meses: 'caracteristicas_n_ingressaram_total_12_meses',
  caracteristicas_n_ingressaram_caf_12_meses: 'caracteristicas_n_ingressaram_caf_12_meses',
  sim_nao_producao: 'sim_nao_producao',
  sim_nao_file: 'sim_nao_file',
  sim_nao_pj: 'sim_nao_pj',
  sim_nao_socio: 'sim_nao_socio',
  obs: 'obs',
  descricao: 'descricao',
  eixos_trabalhados: 'eixos_trabalhados',
  enfase: 'enfase',
  enfase_outros: 'enfase_outros',
  metodologia: 'metodologia',
  orientacoes: 'orientacoes',
  plano_gestao_rascunho: 'plano_gestao_rascunho',
  plano_gestao_rascunho_updated_by: 'plano_gestao_rascunho_updated_by',
  plano_gestao_rascunho_updated_at: 'plano_gestao_rascunho_updated_at',
  plano_gestao_relatorio_sintetico: 'plano_gestao_relatorio_sintetico',
  plano_gestao_relatorio_sintetico_updated_by: 'plano_gestao_relatorio_sintetico_updated_by',
  plano_gestao_relatorio_sintetico_updated_at: 'plano_gestao_relatorio_sintetico_updated_at',
  plano_gestao_validacao_status: 'plano_gestao_validacao_status',
  plano_gestao_validacao_usuario: 'plano_gestao_validacao_usuario',
  plano_gestao_validacao_data: 'plano_gestao_validacao_data',
  plano_gestao_validacao_obs: 'plano_gestao_validacao_obs',
  participantes_menos_10: 'participantes_menos_10',
  assinatura_rep_legal: 'assinatura_rep_legal',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  model_version: 'model_version',
  ui_version: 'ui_version',
  is_complete: 'is_complete',
  submission_date: 'submission_date',
  marked_as_complete_date: 'marked_as_complete_date',
  complementado: 'complementado',
  validacao_status: 'validacao_status',
  validacao_usuario: 'validacao_usuario',
  validacao_data: 'validacao_data',
  validacao_obs: 'validacao_obs'
};

exports.Prisma.Organizacao_abrangencia_pjScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  razao_social: 'razao_social',
  sigla: 'sigla',
  cnpj_pj: 'cnpj_pj',
  num_socios_caf: 'num_socios_caf',
  num_socios_total: 'num_socios_total',
  estado: 'estado',
  municipio: 'municipio',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Organizacao_abrangencia_socioScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  num_socios: 'num_socios',
  estado: 'estado',
  municipio: 'municipio',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Organizacao_arquivoScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  arquivo: 'arquivo',
  obs: 'obs',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Organizacao_documentoScalarFieldEnum = {
  id: 'id',
  id_organizacao: 'id_organizacao',
  tipo_documento: 'tipo_documento',
  arquivo: 'arquivo',
  data_envio: 'data_envio',
  usuario_envio: 'usuario_envio',
  obs: 'obs'
};

exports.Prisma.Organizacao_fotoScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  grupo: 'grupo',
  foto: 'foto',
  obs: 'obs',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Organizacao_indicadorScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  valor: 'valor',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Organizacao_participanteScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  nome: 'nome',
  cpf: 'cpf',
  telefone: 'telefone',
  relacao: 'relacao',
  relacao_outros: 'relacao_outros',
  assinatura: 'assinatura',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Organizacao_producaoScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  parent_auri: 'parent_auri',
  ordinal_number: 'ordinal_number',
  top_level_auri: 'top_level_auri',
  cultura: 'cultura',
  anual: 'anual',
  mensal: 'mensal',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.RolesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  moduleId: 'moduleId'
};

exports.Prisma.System_settingsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  type: 'type',
  description: 'description',
  category: 'category',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.User_rolesScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EnfaseScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.EstadoScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.FuncaoScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.GrupoScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.IndicadorScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.Municipio_ibgeScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao',
  id_estado: 'id_estado'
};

exports.Prisma.PaaScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.RelacaoScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.RespostaScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.Sim_naoScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.Plano_gestao_acao_modeloScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  titulo: 'titulo',
  grupo: 'grupo',
  acao: 'acao',
  hint_como_sera_feito: 'hint_como_sera_feito',
  hint_responsavel: 'hint_responsavel',
  hint_recursos: 'hint_recursos',
  ordem: 'ordem',
  ativo: 'ativo'
};

exports.Prisma.Plano_gestao_acaoScalarFieldEnum = {
  id: 'id',
  id_organizacao: 'id_organizacao',
  id_acao_modelo: 'id_acao_modelo',
  acao: 'acao',
  responsavel: 'responsavel',
  data_inicio: 'data_inicio',
  data_termino: 'data_termino',
  como_sera_feito: 'como_sera_feito',
  recursos: 'recursos',
  created_at: 'created_at',
  updated_at: 'updated_at',
  adicionada: 'adicionada',
  suprimida: 'suprimida',
  tipo_plano: 'tipo_plano',
  grupo_plano: 'grupo_plano'
};

exports.Prisma.Organizacao_tecnicoScalarFieldEnum = {
  id: 'id',
  id_organizacao: 'id_organizacao',
  id_tecnico: 'id_tecnico',
  created_at: 'created_at',
  created_by: 'created_by'
};

exports.Prisma.Plano_gestao_evidenciaScalarFieldEnum = {
  id: 'id',
  id_organizacao: 'id_organizacao',
  tipo: 'tipo',
  nome_arquivo: 'nome_arquivo',
  caminho_arquivo: 'caminho_arquivo',
  descricao: 'descricao',
  uploaded_by: 'uploaded_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.QualificacaoScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  objetivo_geral: 'objetivo_geral',
  objetivos_especificos: 'objetivos_especificos',
  conteudo_programatico: 'conteudo_programatico',
  metodologia: 'metodologia',
  recursos_didaticos: 'recursos_didaticos',
  estrategia_avaliacao: 'estrategia_avaliacao',
  referencias: 'referencias',
  ativo: 'ativo',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  validacao_status: 'validacao_status',
  validacao_usuario: 'validacao_usuario',
  validacao_data: 'validacao_data',
  validacao_obs: 'validacao_obs'
};

exports.Prisma.Qualificacao_organizacaoScalarFieldEnum = {
  id_qualificacao: 'id_qualificacao',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Qualificacao_instrutorScalarFieldEnum = {
  id_qualificacao: 'id_qualificacao',
  id_instrutor: 'id_instrutor'
};

exports.Prisma.Qualificacao_tecnicoScalarFieldEnum = {
  id: 'id',
  id_qualificacao: 'id_qualificacao',
  id_tecnico: 'id_tecnico',
  created_at: 'created_at',
  created_by: 'created_by'
};

exports.Prisma.CapacitacaoScalarFieldEnum = {
  id: 'id',
  id_qualificacao: 'id_qualificacao',
  titulo: 'titulo',
  data_inicio: 'data_inicio',
  data_fim: 'data_fim',
  local: 'local',
  turno: 'turno',
  status: 'status',
  link_inscricao: 'link_inscricao',
  link_avaliacao: 'link_avaliacao',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  validacao_status: 'validacao_status',
  validacao_usuario: 'validacao_usuario',
  validacao_data: 'validacao_data',
  validacao_obs: 'validacao_obs'
};

exports.Prisma.Capacitacao_organizacaoScalarFieldEnum = {
  id_capacitacao: 'id_capacitacao',
  id_organizacao: 'id_organizacao'
};

exports.Prisma.Capacitacao_tecnicoScalarFieldEnum = {
  id: 'id',
  id_capacitacao: 'id_capacitacao',
  id_tecnico: 'id_tecnico',
  created_at: 'created_at',
  created_by: 'created_by'
};

exports.Prisma.Capacitacao_inscricaoScalarFieldEnum = {
  id: 'id',
  id_capacitacao: 'id_capacitacao',
  nome: 'nome',
  email: 'email',
  telefone: 'telefone',
  instituicao: 'instituicao',
  cpf: 'cpf',
  rg: 'rg',
  inscrito_por: 'inscrito_por',
  created_at: 'created_at'
};

exports.Prisma.Capacitacao_presencaScalarFieldEnum = {
  id: 'id',
  id_capacitacao: 'id_capacitacao',
  id_inscricao: 'id_inscricao',
  nome: 'nome',
  presente: 'presente',
  data: 'data',
  created_by: 'created_by',
  created_at: 'created_at'
};

exports.Prisma.Avaliacao_versaoScalarFieldEnum = {
  id: 'id',
  versao: 'versao',
  descricao: 'descricao',
  ativo: 'ativo',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by'
};

exports.Prisma.Avaliacao_perguntaScalarFieldEnum = {
  id: 'id',
  id_versao: 'id_versao',
  ordem: 'ordem',
  texto_pergunta: 'texto_pergunta',
  tipo: 'tipo',
  opcoes: 'opcoes',
  obrigatoria: 'obrigatoria',
  created_at: 'created_at'
};

exports.Prisma.Capacitacao_avaliacaoScalarFieldEnum = {
  id: 'id',
  id_capacitacao: 'id_capacitacao',
  id_versao_avaliacao: 'id_versao_avaliacao',
  id_inscricao: 'id_inscricao',
  nome_participante: 'nome_participante',
  email_participante: 'email_participante',
  telefone_participante: 'telefone_participante',
  comentarios: 'comentarios',
  created_at: 'created_at'
};

exports.Prisma.Capacitacao_avaliacao_respostaScalarFieldEnum = {
  id: 'id',
  id_avaliacao: 'id_avaliacao',
  id_pergunta: 'id_pergunta',
  resposta_texto: 'resposta_texto',
  resposta_opcao: 'resposta_opcao',
  created_at: 'created_at'
};

exports.Prisma.Capacitacao_materialScalarFieldEnum = {
  id: 'id',
  id_qualificacao: 'id_qualificacao',
  nome_arquivo: 'nome_arquivo',
  nome_original: 'nome_original',
  caminho_arquivo: 'caminho_arquivo',
  tamanho_bytes: 'tamanho_bytes',
  tipo_mime: 'tipo_mime',
  descricao: 'descricao',
  uploaded_by: 'uploaded_by',
  created_at: 'created_at'
};

exports.Prisma.Capacitacao_evidenciaScalarFieldEnum = {
  id: 'id',
  id_capacitacao: 'id_capacitacao',
  tipo: 'tipo',
  nome_arquivo: 'nome_arquivo',
  caminho_arquivo: 'caminho_arquivo',
  descricao: 'descricao',
  data_evidencia: 'data_evidencia',
  local_evidencia: 'local_evidencia',
  uploaded_by: 'uploaded_by',
  created_at: 'created_at'
};

exports.Prisma.GlebaScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao',
  municipio: 'municipio',
  id_municipio: 'id_municipio',
  estado: 'estado',
  id_estado: 'id_estado',
  pasta: 'pasta'
};

exports.Prisma.Estado_familiasScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao',
  uf: 'uf',
  id_unit: 'id_unit'
};

exports.Prisma.Municipio_ibge_familiasScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao',
  id_estado: 'id_estado',
  uf: 'uf',
  modulo_fiscal: 'modulo_fiscal'
};

exports.Prisma.ValidacaoScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.Validacao_estagiarioScalarFieldEnum = {
  id: 'id',
  descricao: 'descricao'
};

exports.Prisma.Familias_individualScalarFieldEnum = {
  id: 'id',
  uri: 'uri',
  creator_uri_user: 'creator_uri_user',
  creation_date: 'creation_date',
  last_update_uri_user: 'last_update_uri_user',
  last_update_date: 'last_update_date',
  model_version: 'model_version',
  ui_version: 'ui_version',
  is_complete: 'is_complete',
  submission_date: 'submission_date',
  marked_as_complete_date: 'marked_as_complete_date',
  estado: 'estado',
  municipio: 'municipio',
  cod_gleba: 'cod_gleba',
  comunidade: 'comunidade',
  quilombo: 'quilombo',
  gps_lat: 'gps_lat',
  gps_lng: 'gps_lng',
  gps_alt: 'gps_alt',
  gps_acc: 'gps_acc',
  deviceid: 'deviceid',
  meta_instance_id: 'meta_instance_id',
  meta_instance_name: 'meta_instance_name',
  inicio: 'inicio',
  fim: 'fim',
  validacao: 'validacao',
  obs_validacao: 'obs_validacao',
  tecnico: 'tecnico',
  estagiario: 'estagiario',
  validacao_estagiario: 'validacao_estagiario',
  data_hora_alterado: 'data_hora_alterado',
  data_hora_validado: 'data_hora_validado',
  removido: 'removido',
  formulario_completo: 'formulario_completo',
  obs_gerais: 'obs_gerais',
  n_moradores: 'n_moradores',
  tipo_formulario: 'tipo_formulario',
  num_imovel: 'num_imovel',
  aceitou_visita: 'aceitou_visita',
  tem_nome: 'tem_nome',
  iuf_ocup_nome: 'iuf_ocup_nome',
  iuf_ocup_cpf: 'iuf_ocup_cpf',
  iuf_conj_nome: 'iuf_conj_nome',
  iuf_conj_cpf: 'iuf_conj_cpf',
  iuf_desc_acesso: 'iuf_desc_acesso',
  iuf_ocup_conhecido: 'iuf_ocup_conhecido',
  iuf_ocup_sexo: 'iuf_ocup_sexo',
  iuf_ocup_d_nascimento: 'iuf_ocup_d_nascimento',
  iuf_ocup_idade: 'iuf_ocup_idade',
  iuf_ocup_nacionalidade: 'iuf_ocup_nacionalidade',
  iuf_ocup_n_estado: 'iuf_ocup_n_estado',
  iuf_ocup_n_municipio_int: 'iuf_ocup_n_municipio_int',
  iuf_ocup_nd_identidade: 'iuf_ocup_nd_identidade',
  iuf_ocup_nd_tipo: 'iuf_ocup_nd_tipo',
  iuf_ocup_nd_orgao: 'iuf_ocup_nd_orgao',
  iuf_ocup_nd_uf: 'iuf_ocup_nd_uf',
  iuf_ocup_e_civil: 'iuf_ocup_e_civil',
  iuf_ocup_d_casamento: 'iuf_ocup_d_casamento',
  iuf_ocup_r_bens: 'iuf_ocup_r_bens',
  iuf_ocup_n_mae: 'iuf_ocup_n_mae',
  iuf_ocup_profissao: 'iuf_ocup_profissao',
  iuf_ocup_profissao_outros: 'iuf_ocup_profissao_outros',
  iuf_ocup_aposentado: 'iuf_ocup_aposentado',
  iuf_ocup_tel1: 'iuf_ocup_tel1',
  iuf_ocup_tel2: 'iuf_ocup_tel2',
  iuf_ocup_email: 'iuf_ocup_email',
  iuf_conj_conhecido: 'iuf_conj_conhecido',
  iuf_conj_sexo: 'iuf_conj_sexo',
  iuf_conj_d_nascimento: 'iuf_conj_d_nascimento',
  iuf_conj_idade: 'iuf_conj_idade',
  iuf_conj_nacionalidade: 'iuf_conj_nacionalidade',
  iuf_conj_n_estado: 'iuf_conj_n_estado',
  iuf_conj_n_municipio_int: 'iuf_conj_n_municipio_int',
  iuf_conj_nd_identidade: 'iuf_conj_nd_identidade',
  iuf_conj_nd_tipo: 'iuf_conj_nd_tipo',
  iuf_conj_nd_orgao: 'iuf_conj_nd_orgao',
  iuf_conj_nd_uf: 'iuf_conj_nd_uf',
  iuf_conj_e_civil: 'iuf_conj_e_civil',
  iuf_conj_d_casamento: 'iuf_conj_d_casamento',
  iuf_conj_r_bens: 'iuf_conj_r_bens',
  iuf_conj_n_mae: 'iuf_conj_n_mae',
  iuf_conj_profissao: 'iuf_conj_profissao',
  iuf_conj_profissao_outros: 'iuf_conj_profissao_outros',
  iuf_conj_aposentado: 'iuf_conj_aposentado',
  iuf_conj_tel1: 'iuf_conj_tel1',
  iuf_conj_tel2: 'iuf_conj_tel2',
  iuf_conj_email: 'iuf_conj_email',
  ec_zona: 'ec_zona',
  ec_logrado: 'ec_logrado',
  ec_numero: 'ec_numero',
  ec_complem: 'ec_complem',
  ec_bairro: 'ec_bairro',
  ec_cep: 'ec_cep',
  ec_uf: 'ec_uf',
  ec_cod_ibg: 'ec_cod_ibg',
  ii_titulo_definitivo: 'ii_titulo_definitivo',
  ii_titulo_quitado: 'ii_titulo_quitado',
  ii_titulo_baixa: 'ii_titulo_baixa',
  ii_linha_credito: 'ii_linha_credito',
  ii_linha_credito_qual: 'ii_linha_credito_qual',
  ii_fr_regularizacao: 'ii_fr_regularizacao',
  ii_fr_r_doc: 'ii_fr_r_doc',
  ii_fr_r_doc_outro: 'ii_fr_r_doc_outro',
  ii_p_principal: 'ii_p_principal',
  ii_r_st: 'ii_r_st',
  ii_do_originaria: 'ii_do_originaria',
  ii_do_atual: 'ii_do_atual',
  ii_o_primitivo: 'ii_o_primitivo',
  ii_din_urbano: 'ii_din_urbano',
  ii_c_acesso: 'ii_c_acesso',
  ii_car_possui: 'ii_car_possui',
  ii_car_protocolo: 'ii_car_protocolo',
  ii_georreferenciada: 'ii_georreferenciada',
  ii_ai_matricula: 'ii_ai_matricula',
  ii_declarada_medida: 'ii_declarada_medida',
  ii_vm_fiscal: 'ii_vm_fiscal',
  ii_d_possui: 'ii_d_possui',
  ii_d_orgaopublico: 'ii_d_orgaopublico',
  ii_d_orgaopublico_outros: 'ii_d_orgaopublico_outros',
  ii_d_cc_td: 'ii_d_cc_td',
  ii_d_cc_ccdru: 'ii_d_cc_ccdru',
  ii_d_sncr: 'ii_d_sncr',
  ii_d_certific: 'ii_d_certific',
  ii_d_comprobatoria: 'ii_d_comprobatoria',
  ii_d_comprobatoria_outros: 'ii_d_comprobatoria_outros',
  qa_a_sede: 'qa_a_sede',
  qa_a_p_proprio: 'qa_a_p_proprio',
  qa_a_m_nativa: 'qa_a_m_nativa',
  qa_a_florestada: 'qa_a_florestada',
  qa_a_pousio: 'qa_a_pousio',
  qa_a_p_nativa: 'qa_a_p_nativa',
  qa_a_p_plantada: 'qa_a_p_plantada',
  qa_a_degradada: 'qa_a_degradada',
  rrf_p_cultura: 'rrf_p_cultura',
  rrf_eo_direta: 'rrf_eo_direta',
  rrf_eo_forma: 'rrf_eo_forma',
  rrf_ed_anterior: 'rrf_ed_anterior',
  rrf_ed_anterior_quem: 'rrf_ed_anterior_quem',
  rrf_oc_proprietario: 'rrf_oc_proprietario',
  rrf_oc_proprietario_quem: 'rrf_oc_proprietario_quem',
  rrf_oc_escravo: 'rrf_oc_escravo',
  rrf_oc_escravo_quem: 'rrf_oc_escravo_quem',
  rrf_oc_beneficiado: 'rrf_oc_beneficiado',
  rrf_oc_beneficiado_quem: 'rrf_oc_beneficiado_quem',
  rrf_oc_crime: 'rrf_oc_crime',
  rrf_oc_crime_quem: 'rrf_oc_crime_quem',
  rrf_oc_cargo: 'rrf_oc_cargo',
  ir_r_bruta: 'ir_r_bruta',
  ir_r_e_lote: 'ir_r_e_lote',
  ir_f_p_social: 'ir_f_p_social',
  ir_f_p_social_outro: 'ir_f_p_social_outro',
  sb_moradia_outro: 'sb_moradia_outro',
  sb_agua_outro: 'sb_agua_outro',
  sb_agua_suficiente: 'sb_agua_suficiente',
  sb_d_residuo: 'sb_d_residuo',
  sb_d_residuo_outro: 'sb_d_residuo_outro',
  san_tiveram_preocupacao: 'san_tiveram_preocupacao',
  san_preocupacao: 'san_preocupacao',
  san_acabaram_antes: 'san_acabaram_antes',
  san_acabou: 'san_acabou',
  san_ficaram_sem: 'san_ficaram_sem',
  san_sem_dinheiro: 'san_sem_dinheiro',
  san_comeram_pouco: 'san_comeram_pouco',
  san_deixou_refeicao: 'san_deixou_refeicao',
  san_comeu_menos_devia: 'san_comeu_menos_devia',
  san_comeu_menos: 'san_comeu_menos',
  san_sentiu_fome: 'san_sentiu_fome',
  san_uma_refeicao: 'san_uma_refeicao',
  san_refeicao_completa: 'san_refeicao_completa',
  san_orientacao_profissional: 'san_orientacao_profissional',
  san_orientacao: 'san_orientacao',
  pa_a_vegetal_outros: 'pa_a_vegetal_outros',
  pa_p_vegetal_outros: 'pa_p_vegetal_outros'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  audit_logs: 'audit_logs',
  db_connections: 'db_connections',
  modules: 'modules',
  organizacao: 'organizacao',
  organizacao_abrangencia_pj: 'organizacao_abrangencia_pj',
  organizacao_abrangencia_socio: 'organizacao_abrangencia_socio',
  organizacao_arquivo: 'organizacao_arquivo',
  organizacao_documento: 'organizacao_documento',
  organizacao_foto: 'organizacao_foto',
  organizacao_indicador: 'organizacao_indicador',
  organizacao_participante: 'organizacao_participante',
  organizacao_producao: 'organizacao_producao',
  roles: 'roles',
  system_settings: 'system_settings',
  user_roles: 'user_roles',
  users: 'users',
  enfase: 'enfase',
  estado: 'estado',
  funcao: 'funcao',
  grupo: 'grupo',
  indicador: 'indicador',
  municipio_ibge: 'municipio_ibge',
  paa: 'paa',
  relacao: 'relacao',
  resposta: 'resposta',
  sim_nao: 'sim_nao',
  plano_gestao_acao_modelo: 'plano_gestao_acao_modelo',
  plano_gestao_acao: 'plano_gestao_acao',
  organizacao_tecnico: 'organizacao_tecnico',
  plano_gestao_evidencia: 'plano_gestao_evidencia',
  qualificacao: 'qualificacao',
  qualificacao_organizacao: 'qualificacao_organizacao',
  qualificacao_instrutor: 'qualificacao_instrutor',
  qualificacao_tecnico: 'qualificacao_tecnico',
  capacitacao: 'capacitacao',
  capacitacao_organizacao: 'capacitacao_organizacao',
  capacitacao_tecnico: 'capacitacao_tecnico',
  capacitacao_inscricao: 'capacitacao_inscricao',
  capacitacao_presenca: 'capacitacao_presenca',
  avaliacao_versao: 'avaliacao_versao',
  avaliacao_pergunta: 'avaliacao_pergunta',
  capacitacao_avaliacao: 'capacitacao_avaliacao',
  capacitacao_avaliacao_resposta: 'capacitacao_avaliacao_resposta',
  capacitacao_material: 'capacitacao_material',
  capacitacao_evidencia: 'capacitacao_evidencia',
  gleba: 'gleba',
  estado_familias: 'estado_familias',
  municipio_ibge_familias: 'municipio_ibge_familias',
  validacao: 'validacao',
  validacao_estagiario: 'validacao_estagiario',
  familias_individual: 'familias_individual'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
