import {
  CheckCircle,
  XCircle,
  Map,
  BarChart,
  Users,
  Clipboard,
  Plus,
  Edit,
  Trash,
  Search,
  Settings,
  TrendingUp,
  Bell,
  Mail,
  Lock,
  Lightbulb,
  Rocket,
  Tag,
  Calendar,
  Sparkles,
  Wrench,
  Hammer,
  TrendingDown,
  Eye,
  EyeOff,
  Monitor,
  Timer,
  AlertTriangle,
  Info,
  Sliders,
  Building,
  Building2,
  ArrowUpDown,
  AlertCircle,
  Home,
  User,
  FileText,
  Layers,
  Globe
} from 'lucide-react';

// Mapeamento de emojis para ícones Lucide React
export const emojiToIconMap = {
  '✅': CheckCircle,
  '❌': XCircle,
  '🗺️': Map,
  '📊': BarChart,
  '👥': Users,
  '📋': Clipboard,
  '➕': Plus,
  '✏️': Edit,
  '🗑️': Trash,
  '🔍': Search,
  '⚙️': Settings,
  '📈': TrendingUp,
  '🔔': Bell,
  '📧': Mail,
  '🔐': Lock,
  '💡': Lightbulb,
  '🚀': Rocket,
  '🏷️': Tag,
  '📅': Calendar,
  '✨': Sparkles,
  '🔧': Wrench,
  '🛠️': Hammer,
  '📉': TrendingDown,
  '👁️': Eye,
  '🙈': EyeOff,
  '🖥️': Monitor,
  '⏱️': Timer,
  '⚠️': AlertTriangle,
  'ℹ️': Info,
  '🎛️': Sliders,
  '🏗️': Building,
  '🏛️': Building2,
  '↕️': ArrowUpDown,
  '🏠': Home,
  '👤': User,
  '📄': FileText,
  '📚': Layers,
  '🌍': Globe
} as const;

// Tipos para o mapeamento
export type EmojiKey = keyof typeof emojiToIconMap;
export type IconComponent = typeof emojiToIconMap[EmojiKey];
