-- pinovara.organizacao definition

-- Drop table

-- DROP TABLE pinovara.organizacao;

CREATE TABLE pinovara.organizacao (
	id serial4 NOT NULL,
	inicio timestamp NULL,
	fim timestamp NULL,
	deviceid varchar NULL,
	data_visita timestamp NULL,
	estado int4 NULL,
	municipio int4 NULL,
	gps_lat float8 NULL,
	gps_lng float8 NULL,
	gps_alt float8 NULL,
	gps_acc float8 NULL,
	nome varchar NULL,
	cnpj varchar NULL,
	telefone varchar NULL,
	email varchar NULL,
	data_fundacao timestamp NULL,
	organizacao_end_logradouro varchar NULL,
	organizacao_end_bairro varchar NULL,
	organizacao_end_complemento varchar NULL,
	organizacao_end_numero varchar NULL,
	organizacao_end_cep varchar(8) NULL,
	representante_nome varchar NULL,
	representante_cpf varchar(11) NULL,
	representante_rg varchar NULL,
	representante_telefone varchar NULL,
	representante_email varchar NULL,
	representante_end_logradouro varchar NULL,
	representante_end_bairro varchar NULL,
	representante_end_complemento varchar NULL,
	representante_end_numero varchar NULL,
	representante_end_cep varchar(8) NULL,
	representante_funcao int4 NULL,
	caracteristicas_n_total_socios int4 NULL,
	caracteristicas_n_total_socios_caf int4 NULL,
	caracteristicas_n_distintos_caf int4 NULL,
	caracteristicas_n_socios_paa int4 NULL,
	caracteristicas_n_naosocios_paa int4 NULL,
	caracteristicas_n_socios_pnae int4 NULL,
	caracteristicas_n_naosocios_pnae int4 NULL,
	caracteristicas_n_ativos_total int4 NULL,
	caracteristicas_n_ativos_caf int4 NULL,
	caracteristicas_n_naosocio_op_total int4 NULL,
	caracteristicas_n_naosocio_op_caf int4 NULL,
	caracteristicas_ta_a_mulher int4 NULL,
	caracteristicas_ta_a_homem int4 NULL,
	caracteristicas_ta_e_mulher int4 NULL,
	caracteristicas_ta_e_homem int4 NULL,
	caracteristicas_ta_o_mulher int4 NULL,
	caracteristicas_ta_o_homem int4 NULL,
	caracteristicas_ta_i_mulher int4 NULL,
	caracteristicas_ta_i_homem int4 NULL,
	caracteristicas_ta_p_mulher int4 NULL,
	caracteristicas_ta_p_homem int4 NULL,
	caracteristicas_ta_af_mulher int4 NULL,
	caracteristicas_ta_af_homem int4 NULL,
	caracteristicas_ta_q_mulher int4 NULL,
	caracteristicas_ta_q_homem int4 NULL,
	caracteristicas_ta_caf_convencional int4 NULL,
	caracteristicas_ta_caf_agroecologico int4 NULL,
	caracteristicas_ta_caf_transicao int4 NULL,
	caracteristicas_ta_caf_organico int4 NULL,
	go_organizacao_7_resposta int4 NULL,
	go_organizacao_7_comentario varchar NULL,
	go_organizacao_7_proposta varchar NULL,
	go_organizacao_8_resposta int4 NULL,
	go_organizacao_8_comentario varchar NULL,
	go_organizacao_8_proposta varchar NULL,
	go_organizacao_9_resposta int4 NULL,
	go_organizacao_9_comentario varchar NULL,
	go_organizacao_9_proposta varchar NULL,
	go_organizacao_10_resposta int4 NULL,
	go_organizacao_10_comentario varchar NULL,
	go_organizacao_10_proposta varchar NULL,
	go_organizacao_11_resposta int4 NULL,
	go_organizacao_11_comentario varchar NULL,
	go_organizacao_11_proposta varchar NULL,
	go_organizacao_12_resposta int4 NULL,
	go_organizacao_12_comentario varchar NULL,
	go_organizacao_12_proposta varchar NULL,
	go_organizacao_13_resposta int4 NULL,
	go_organizacao_13_comentario varchar NULL,
	go_organizacao_13_proposta varchar NULL,
	go_direcao_14_resposta int4 NULL,
	go_direcao_14_comentario varchar NULL,
	go_direcao_14_proposta varchar NULL,
	go_direcao_15_resposta int4 NULL,
	go_direcao_15_comentario varchar NULL,
	go_direcao_15_proposta varchar NULL,
	go_direcao_16_resposta int4 NULL,
	go_direcao_16_comentario varchar NULL,
	go_direcao_16_proposta varchar NULL,
	go_direcao_17_resposta int4 NULL,
	go_direcao_17_comentario varchar NULL,
	go_direcao_17_proposta varchar NULL,
	go_direcao_18_resposta int4 NULL,
	go_direcao_18_comentario varchar NULL,
	go_direcao_18_proposta varchar NULL,
	go_direcao_19_resposta int4 NULL,
	go_direcao_19_comentario varchar NULL,
	go_direcao_19_proposta varchar NULL,
	go_direcao_20_resposta int4 NULL,
	go_direcao_20_comentario varchar NULL,
	go_direcao_20_proposta varchar NULL,
	go_direcao_21_resposta int4 NULL,
	go_direcao_21_comentario varchar NULL,
	go_direcao_21_proposta varchar NULL,
	go_controle_20_resposta int4 NULL,
	go_controle_20_comentario varchar NULL,
	go_controle_20_proposta varchar NULL,
	go_controle_21_resposta int4 NULL,
	go_controle_21_comentario varchar NULL,
	go_controle_21_proposta varchar NULL,
	go_controle_22_resposta int4 NULL,
	go_controle_22_comentario varchar NULL,
	go_controle_22_proposta varchar NULL,
	go_controle_23_resposta int4 NULL,
	go_controle_23_comentario varchar NULL,
	go_controle_23_proposta varchar NULL,
	go_controle_24_resposta int4 NULL,
	go_controle_24_comentario varchar NULL,
	go_controle_24_proposta varchar NULL,
	go_controle_25_resposta int4 NULL,
	go_controle_25_comentario varchar NULL,
	go_controle_25_proposta varchar NULL,
	go_educacao_26_resposta int4 NULL,
	go_educacao_26_comentario varchar NULL,
	go_educacao_26_proposta varchar NULL,
	go_educacao_27_resposta int4 NULL,
	go_educacao_27_comentario varchar NULL,
	go_educacao_27_proposta varchar NULL,
	go_educacao_28_resposta int4 NULL,
	go_educacao_28_comentario varchar NULL,
	go_educacao_28_proposta varchar NULL,
	go_estrategia_5_resposta int4 NULL,
	go_estrategia_5_comentario varchar NULL,
	go_estrategia_5_proposta varchar NULL,
	go_estrategia_6_resposta int4 NULL,
	go_estrategia_6_comentario varchar NULL,
	go_estrategia_6_proposta varchar NULL,
	go_estrutura_1_resposta int4 NULL,
	go_estrutura_1_comentario varchar NULL,
	go_estrutura_1_proposta varchar NULL,
	go_estrutura_2_resposta int4 NULL,
	go_estrutura_2_comentario varchar NULL,
	go_estrutura_2_proposta varchar NULL,
	go_estrutura_3_resposta int4 NULL,
	go_estrutura_3_comentario varchar NULL,
	go_estrutura_3_proposta varchar NULL,
	go_estrutura_4_resposta int4 NULL,
	go_estrutura_4_comentario varchar NULL,
	go_estrutura_4_proposta varchar NULL,
	gpp_planejamento_4_resposta int4 NULL,
	gpp_planejamento_4_comentario varchar NULL,
	gpp_planejamento_4_proposta varchar NULL,
	gpp_planejamento_5_resposta int4 NULL,
	gpp_planejamento_5_comentario varchar NULL,
	gpp_planejamento_5_proposta varchar NULL,
	gpp_planejamento_6_resposta int4 NULL,
	gpp_planejamento_6_comentario varchar NULL,
	gpp_planejamento_6_proposta varchar NULL,
	gpp_logistica_7_resposta int4 NULL,
	gpp_logistica_7_comentario varchar NULL,
	gpp_logistica_7_proposta varchar NULL,
	gpp_logistica_8_resposta int4 NULL,
	gpp_logistica_8_comentario varchar NULL,
	gpp_logistica_8_proposta varchar NULL,
	gpp_logistica_9_resposta int4 NULL,
	gpp_logistica_9_comentario varchar NULL,
	gpp_logistica_9_proposta varchar NULL,
	gpp_logistica_10_resposta int4 NULL,
	gpp_logistica_10_comentario varchar NULL,
	gpp_logistica_10_proposta varchar NULL,
	gpp_logistica_11_resposta int4 NULL,
	gpp_logistica_11_comentario varchar NULL,
	gpp_logistica_11_proposta varchar NULL,
	gpp_logistica_12_resposta int4 NULL,
	gpp_logistica_12_comentario varchar NULL,
	gpp_logistica_12_proposta varchar NULL,
	gpp_valor_13_resposta int4 NULL,
	gpp_valor_13_comentario varchar NULL,
	gpp_valor_13_proposta varchar NULL,
	gpp_valor_14_resposta int4 NULL,
	gpp_valor_14_comentario varchar NULL,
	gpp_valor_14_proposta varchar NULL,
	gpp_valor_15_resposta int4 NULL,
	gpp_valor_15_comentario varchar NULL,
	gpp_valor_15_proposta varchar NULL,
	gpp_fluxo_16_resposta int4 NULL,
	gpp_fluxo_16_comentario varchar NULL,
	gpp_fluxo_16_proposta varchar NULL,
	gpp_fluxo_17_resposta int4 NULL,
	gpp_fluxo_17_comentario varchar NULL,
	gpp_fluxo_17_proposta varchar NULL,
	gpp_fluxo_18_resposta int4 NULL,
	gpp_fluxo_18_comentario varchar NULL,
	gpp_fluxo_18_proposta varchar NULL,
	gpp_fluxo_19_resposta int4 NULL,
	gpp_fluxo_19_comentario varchar NULL,
	gpp_fluxo_19_proposta varchar NULL,
	gpp_fluxo_20_resposta int4 NULL,
	gpp_fluxo_20_comentario varchar NULL,
	gpp_fluxo_20_proposta varchar NULL,
	gpp_fluxo_21_resposta int4 NULL,
	gpp_fluxo_21_comentario varchar NULL,
	gpp_fluxo_21_proposta varchar NULL,
	gpp_fluxo_22_resposta int4 NULL,
	gpp_fluxo_22_comentario varchar NULL,
	gpp_fluxo_22_proposta varchar NULL,
	gpp_qualidade_23_resposta int4 NULL,
	gpp_qualidade_23_comentario varchar NULL,
	gpp_qualidade_23_proposta varchar NULL,
	gpp_qualidade_24_resposta int4 NULL,
	gpp_qualidade_24_comentario varchar NULL,
	gpp_qualidade_24_proposta varchar NULL,
	gpp_qualidade_25_resposta int4 NULL,
	gpp_qualidade_25_comentario varchar NULL,
	gpp_qualidade_25_proposta varchar NULL,
	gpp_qualidade_26_resposta int4 NULL,
	gpp_qualidade_26_comentario varchar NULL,
	gpp_qualidade_26_proposta varchar NULL,
	gpp_qualidade_27_resposta int4 NULL,
	gpp_qualidade_27_comentario varchar NULL,
	gpp_qualidade_27_proposta varchar NULL,
	gpp_qualidade_28_resposta int4 NULL,
	gpp_qualidade_28_comentario varchar NULL,
	gpp_qualidade_28_proposta varchar NULL,
	gpp_producao_29_resposta int4 NULL,
	gpp_producao_29_comentario varchar NULL,
	gpp_producao_29_proposta varchar NULL,
	gpp_reg_sanitaria_1_resposta int4 NULL,
	gpp_reg_sanitaria_1_comentario varchar NULL,
	gpp_reg_sanitaria_1_proposta varchar NULL,
	gpp_reg_sanitaria_2_resposta int4 NULL,
	gpp_reg_sanitaria_2_comentario varchar NULL,
	gpp_reg_sanitaria_2_proposta varchar NULL,
	gpp_reg_sanitaria_3_resposta int4 NULL,
	gpp_reg_sanitaria_3_comentario varchar NULL,
	gpp_reg_sanitaria_3_proposta varchar NULL,
	gc_e_comercial_1_resposta int4 NULL,
	gc_e_comercial_1_comentario varchar NULL,
	gc_e_comercial_1_proposta varchar NULL,
	gc_e_comercial_2_resposta int4 NULL,
	gc_e_comercial_2_comentario varchar NULL,
	gc_e_comercial_2_proposta varchar NULL,
	gc_e_comercial_3_resposta int4 NULL,
	gc_e_comercial_3_comentario varchar NULL,
	gc_e_comercial_3_proposta varchar NULL,
	gc_e_comercial_4_resposta int4 NULL,
	gc_e_comercial_4_comentario varchar NULL,
	gc_e_comercial_4_proposta varchar NULL,
	gc_e_comercial_5_resposta int4 NULL,
	gc_e_comercial_5_comentario varchar NULL,
	gc_e_comercial_5_proposta varchar NULL,
	gc_e_comercial_6_resposta int4 NULL,
	gc_e_comercial_6_comentario varchar NULL,
	gc_e_comercial_6_proposta varchar NULL,
	gc_e_comercial_7_resposta int4 NULL,
	gc_e_comercial_7_comentario varchar NULL,
	gc_e_comercial_7_proposta varchar NULL,
	gc_e_comercial_8_resposta int4 NULL,
	gc_e_comercial_8_comentario varchar NULL,
	gc_e_comercial_8_proposta varchar NULL,
	gc_e_comercial_9_resposta int4 NULL,
	gc_e_comercial_9_comentario varchar NULL,
	gc_e_comercial_9_proposta varchar NULL,
	gc_mercado_10_resposta int4 NULL,
	gc_mercado_10_comentario varchar NULL,
	gc_mercado_10_proposta varchar NULL,
	gc_mercado_11_resposta int4 NULL,
	gc_mercado_11_comentario varchar NULL,
	gc_mercado_11_proposta varchar NULL,
	gc_mercado_12_resposta int4 NULL,
	gc_mercado_12_comentario varchar NULL,
	gc_mercado_12_proposta varchar NULL,
	gc_mercado_13_resposta int4 NULL,
	gc_mercado_13_comentario varchar NULL,
	gc_mercado_13_proposta varchar NULL,
	gc_mercado_14_resposta int4 NULL,
	gc_mercado_14_comentario varchar NULL,
	gc_mercado_14_proposta varchar NULL,
	gc_mercado_15_resposta int4 NULL,
	gc_mercado_15_comentario varchar NULL,
	gc_mercado_15_proposta varchar NULL,
	gc_comercial_15_resposta int4 NULL,
	gc_comercial_15_comentario varchar NULL,
	gc_comercial_15_proposta varchar NULL,
	gc_comercial_16_resposta int4 NULL,
	gc_comercial_16_comentario varchar NULL,
	gc_comercial_16_proposta varchar NULL,
	gc_comercial_17_resposta int4 NULL,
	gc_comercial_17_comentario varchar NULL,
	gc_comercial_17_proposta varchar NULL,
	gc_comercial_18_resposta int4 NULL,
	gc_comercial_18_comentario varchar NULL,
	gc_comercial_18_proposta varchar NULL,
	gc_comercial_19_resposta int4 NULL,
	gc_comercial_19_comentario varchar NULL,
	gc_comercial_19_proposta varchar NULL,
	gc_comercial_20_resposta int4 NULL,
	gc_comercial_20_comentario varchar NULL,
	gc_comercial_20_proposta varchar NULL,
	gc_modelo_21_resposta int4 NULL,
	gc_modelo_21_comentario varchar NULL,
	gc_modelo_21_proposta varchar NULL,
	gc_modelo_22_resposta int4 NULL,
	gc_modelo_22_comentario varchar NULL,
	gc_modelo_22_proposta varchar NULL,
	gc_modelo_23_resposta int4 NULL,
	gc_modelo_23_comentario varchar NULL,
	gc_modelo_23_proposta varchar NULL,
	gc_modelo_24_resposta int4 NULL,
	gc_modelo_24_comentario varchar NULL,
	gc_modelo_24_proposta varchar NULL,
	gc_modelo_25_resposta int4 NULL,
	gc_modelo_25_comentario varchar NULL,
	gc_modelo_25_proposta varchar NULL,
	gc_modelo_26_resposta int4 NULL,
	gc_modelo_26_comentario varchar NULL,
	gc_modelo_26_proposta varchar NULL,
	gc_modelo_27_resposta int4 NULL,
	gc_modelo_27_comentario varchar NULL,
	gc_modelo_27_proposta varchar NULL,
	gf_contas_5_resposta int4 NULL,
	gf_contas_5_comentario varchar NULL,
	gf_contas_5_proposta varchar NULL,
	gf_contas_6_resposta int4 NULL,
	gf_contas_6_comentario varchar NULL,
	gf_contas_6_proposta varchar NULL,
	gf_contas_7_resposta int4 NULL,
	gf_contas_7_comentario varchar NULL,
	gf_contas_7_proposta varchar NULL,
	gf_contas_8_resposta int4 NULL,
	gf_contas_8_comentario varchar NULL,
	gf_contas_8_proposta varchar NULL,
	gf_contas_9_resposta int4 NULL,
	gf_contas_9_comentario varchar NULL,
	gf_contas_9_proposta varchar NULL,
	gf_contas_10_resposta int4 NULL,
	gf_contas_10_comentario varchar NULL,
	gf_contas_10_proposta varchar NULL,
	gf_contas_11_resposta int4 NULL,
	gf_contas_11_comentario varchar NULL,
	gf_contas_11_proposta varchar NULL,
	gf_contas_12_resposta int4 NULL,
	gf_contas_12_comentario varchar NULL,
	gf_contas_12_proposta varchar NULL,
	gf_contas_13_resposta int4 NULL,
	gf_contas_13_comentario varchar NULL,
	gf_caixa_14_resposta int4 NULL,
	gf_caixa_14_comentario varchar NULL,
	gf_caixa_14_proposta varchar NULL,
	gf_caixa_15_resposta int4 NULL,
	gf_caixa_15_comentario varchar NULL,
	gf_caixa_15_proposta varchar NULL,
	gf_caixa_16_resposta int4 NULL,
	gf_caixa_16_comentario varchar NULL,
	gf_caixa_16_proposta varchar NULL,
	gf_estoque_17_resposta int4 NULL,
	gf_estoque_17_comentario varchar NULL,
	gf_estoque_17_proposta varchar NULL,
	gf_estoque_18_resposta int4 NULL,
	gf_estoque_18_comentario varchar NULL,
	gf_estoque_18_proposta varchar NULL,
	gf_estoque_19_resposta int4 NULL,
	gf_estoque_19_comentario varchar NULL,
	gf_estoque_19_proposta varchar NULL,
	gf_resultado_20_resposta int4 NULL,
	gf_resultado_20_comentario varchar NULL,
	gf_resultado_20_proposta varchar NULL,
	gf_resultado_21_resposta int4 NULL,
	gf_resultado_21_comentario varchar NULL,
	gf_resultado_21_proposta varchar NULL,
	gf_analise_22_resposta int4 NULL,
	gf_analise_22_comentario varchar NULL,
	gf_analise_22_proposta varchar NULL,
	gf_analise_23_resposta int4 NULL,
	gf_analise_23_comentario varchar NULL,
	gf_analise_23_proposta varchar NULL,
	gf_analise_24_resposta int4 NULL,
	gf_analise_24_comentario varchar NULL,
	gf_analise_24_proposta varchar NULL,
	gf_fiscal_25_resposta int4 NULL,
	gf_fiscal_25_comentario varchar NULL,
	gf_fiscal_25_proposta varchar NULL,
	gf_fiscal_26_resposta int4 NULL,
	gf_fiscal_26_comentario varchar NULL,
	gf_fiscal_26_proposta varchar NULL,
	gf_balanco_1_resposta int4 NULL,
	gf_balanco_1_comentario varchar NULL,
	gf_balanco_1_proposta varchar NULL,
	gf_balanco_2_resposta int4 NULL,
	gf_balanco_2_comentario varchar NULL,
	gf_balanco_2_proposta varchar NULL,
	gf_balanco_3_resposta int4 NULL,
	gf_balanco_3_comentario varchar NULL,
	gf_balanco_3_proposta varchar NULL,
	gf_balanco_4_resposta int4 NULL,
	gf_balanco_4_comentario varchar NULL,
	gf_balanco_4_proposta varchar NULL,
	gp_p_organizacao_1_resposta int4 NULL,
	gp_p_organizacao_1_comentario varchar NULL,
	gp_p_organizacao_1_proposta varchar NULL,
	gp_p_organizacao_2_resposta int4 NULL,
	gp_p_organizacao_2_comentario varchar NULL,
	gp_p_organizacao_2_proposta varchar NULL,
	gp_p_organizacao_3_resposta int4 NULL,
	gp_p_organizacao_3_comentario varchar NULL,
	gp_p_organizacao_3_proposta varchar NULL,
	gp_p_organizacao_4_resposta int4 NULL,
	gp_p_organizacao_4_comentario varchar NULL,
	gp_p_organizacao_4_proposta varchar NULL,
	gp_p_organizacao_5_resposta int4 NULL,
	gp_p_organizacao_5_comentario varchar NULL,
	gp_p_organizacao_5_proposta varchar NULL,
	gp_p_organizacao_6_resposta int4 NULL,
	gp_p_organizacao_6_comentario varchar NULL,
	gp_p_organizacao_6_proposta varchar NULL,
	gp_p_organizacao_7_resposta int4 NULL,
	gp_p_organizacao_7_comentario varchar NULL,
	gp_p_organizacao_7_proposta varchar NULL,
	gp_p_organizacao_8_resposta int4 NULL,
	gp_p_organizacao_8_comentario varchar NULL,
	gp_p_organizacao_8_proposta varchar NULL,
	gp_p_organizacao_9_resposta int4 NULL,
	gp_p_organizacao_9_comentario varchar NULL,
	gp_p_organizacao_9_proposta varchar NULL,
	gp_p_desenvolvimento_10_resposta int4 NULL,
	gp_p_desenvolvimento_10_comentario varchar NULL,
	gp_p_desenvolvimento_10_proposta varchar NULL,
	gp_p_desenvolvimento_11_resposta int4 NULL,
	gp_p_desenvolvimento_11_comentario varchar NULL,
	gp_p_desenvolvimento_11_proposta varchar NULL,
	gp_p_desenvolvimento_12_resposta int4 NULL,
	gp_p_desenvolvimento_12_comentario varchar NULL,
	gp_p_desenvolvimento_12_proposta varchar NULL,
	gp_p_desenvolvimento_13_resposta int4 NULL,
	gp_p_desenvolvimento_13_comentario varchar NULL,
	gp_p_desenvolvimento_13_proposta varchar NULL,
	gp_trabalho_14_resposta int4 NULL,
	gp_trabalho_14_comentario varchar NULL,
	gp_trabalho_14_proposta varchar NULL,
	gp_trabalho_15_resposta int4 NULL,
	gp_trabalho_15_comentario varchar NULL,
	gp_trabalho_15_proposta varchar NULL,
	gp_trabalho_16_resposta int4 NULL,
	gp_trabalho_16_comentario varchar NULL,
	gp_trabalho_16_proposta varchar NULL,
	gp_trabalho_17_resposta int4 NULL,
	gp_trabalho_17_comentario varchar NULL,
	gp_trabalho_17_proposta varchar NULL,
	gp_geracao_18_resposta int4 NULL,
	gp_geracao_18_comentario varchar NULL,
	gp_geracao_18_proposta varchar NULL,
	gp_geracao_19_resposta int4 NULL,
	gp_geracao_19_comentario varchar NULL,
	gp_geracao_19_proposta varchar NULL,
	gp_geracao_20_resposta int4 NULL,
	gp_geracao_20_comentario varchar NULL,
	gp_geracao_20_proposta varchar NULL,
	gs_socioambiental_1_resposta int4 NULL,
	gs_socioambiental_1_comentario varchar NULL,
	gs_socioambiental_1_proposta varchar NULL,
	gs_socioambiental_2_resposta int4 NULL,
	gs_socioambiental_2_comentario varchar NULL,
	gs_socioambiental_2_proposta varchar NULL,
	gs_socioambiental_3_resposta int4 NULL,
	gs_socioambiental_3_comentario varchar NULL,
	gs_socioambiental_3_proposta varchar NULL,
	gs_socioambiental_4_resposta int4 NULL,
	gs_socioambiental_4_comentario varchar NULL,
	gs_socioambiental_4_proposta varchar NULL,
	gs_socioambiental_5_resposta int4 NULL,
	gs_socioambiental_5_comentario varchar NULL,
	gs_socioambiental_5_proposta varchar NULL,
	gs_ambiental_6_resposta int4 NULL,
	gs_ambiental_6_comentario varchar NULL,
	gs_ambiental_6_proposta varchar NULL,
	gs_ambiental_7_resposta int4 NULL,
	gs_ambiental_7_comentario varchar NULL,
	gs_ambiental_7_proposta varchar NULL,
	gs_ambiental_8_resposta int4 NULL,
	gs_ambiental_8_comentario varchar NULL,
	gs_ambiental_8_proposta varchar NULL,
	gs_ambiental_9_resposta int4 NULL,
	gs_ambiental_9_comentario varchar NULL,
	gs_ambiental_9_proposta varchar NULL,
	gs_reg_ambiental_10_resposta int4 NULL,
	gs_reg_ambiental_10_comentario varchar NULL,
	gs_reg_ambiental_10_proposta varchar NULL,
	gs_reg_ambiental_11_resposta int4 NULL,
	gs_reg_ambiental_11_comentario varchar NULL,
	gs_reg_ambiental_11_proposta varchar NULL,
	gs_reg_ambiental_12_resposta int4 NULL,
	gs_reg_ambiental_12_comentario varchar NULL,
	gs_reg_ambiental_12_proposta varchar NULL,
	gs_reg_ambiental_13_resposta int4 NULL,
	gs_reg_ambiental_13_comentario varchar NULL,
	gs_reg_ambiental_13_proposta varchar NULL,
	gs_reg_ambiental_14_resposta int4 NULL,
	gs_reg_ambiental_14_comentario varchar NULL,
	gs_reg_ambiental_14_proposta varchar NULL,
	gs_impactos_ambiental_15_resposta int4 NULL,
	gs_impactos_ambiental_15_comentario varchar NULL,
	gs_impactos_ambiental_15_proposta varchar NULL,
	gs_impactos_ambiental_16_resposta int4 NULL,
	gs_impactos_ambiental_16_comentario varchar NULL,
	gs_impactos_ambiental_16_proposta varchar NULL,
	gs_impactos_ambiental_17_resposta int4 NULL,
	gs_impactos_ambiental_17_comentario varchar NULL,
	gs_impactos_ambiental_17_proposta varchar NULL,
	gs_impactos_ambiental_18_resposta int4 NULL,
	gs_impactos_ambiental_18_comentario varchar NULL,
	gs_impactos_ambiental_18_proposta varchar NULL,
	gs_impactos_ambiental_19_resposta int4 NULL,
	gs_impactos_ambiental_19_comentario varchar NULL,
	gs_impactos_ambiental_19_proposta varchar NULL,
	gs_impactos_ambiental_20_resposta int4 NULL,
	gs_impactos_ambiental_20_comentario varchar NULL,
	gs_impactos_ambiental_20_proposta varchar NULL,
	gs_impactos_ambiental_21_resposta int4 NULL,
	gs_impactos_ambiental_21_comentario varchar NULL,
	gs_impactos_ambiental_21_proposta varchar NULL,
	gs_impactos_ambiental_22_resposta int4 NULL,
	gs_impactos_ambiental_22_comentario varchar NULL,
	gs_impactos_ambiental_22_proposta varchar NULL,
	gi_iic_1_resposta int4 NULL,
	gi_iic_1_comentario varchar NULL,
	gi_iic_1_proposta varchar NULL,
	gi_iic_2_resposta int4 NULL,
	gi_iic_2_comentario varchar NULL,
	gi_iic_2_proposta varchar NULL,
	gi_iic_3_resposta int4 NULL,
	gi_iic_3_comentario varchar NULL,
	gi_iic_3_proposta varchar NULL,
	gi_iic_4_resposta int4 NULL,
	gi_iic_4_comentario varchar NULL,
	gi_iic_4_proposta varchar NULL,
	gi_iic_5_resposta int4 NULL,
	gi_iic_5_comentario varchar NULL,
	gi_iic_5_proposta varchar NULL,
	gi_mar_6_resposta int4 NULL,
	gi_mar_6_comentario varchar NULL,
	gi_mar_6_proposta varchar NULL,
	gi_mar_7_resposta int4 NULL,
	gi_mar_7_comentario varchar NULL,
	gi_mar_7_proposta varchar NULL,
	gi_mar_8_resposta int4 NULL,
	gi_mar_8_comentario varchar NULL,
	gi_mar_8_proposta varchar NULL,
	gi_mar_9_resposta int4 NULL,
	gi_mar_9_comentario varchar NULL,
	gi_mar_9_proposta varchar NULL,
	gi_time_10_resposta int4 NULL,
	gi_time_10_comentario varchar NULL,
	gi_time_10_proposta varchar NULL,
	gi_time_11_resposta int4 NULL,
	gi_time_11_comentario varchar NULL,
	gi_time_11_proposta varchar NULL,
	gi_time_12_resposta int4 NULL,
	gi_time_12_comentario varchar NULL,
	gi_time_12_proposta varchar NULL,
	gi_time_13_resposta int4 NULL,
	gi_time_13_comentario varchar NULL,
	gi_time_13_proposta varchar NULL,
	gi_time_14_resposta int4 NULL,
	gi_time_14_comentario varchar NULL,
	gi_time_14_proposta varchar NULL,
	is_recursos_naturais_5_resposta int4 NULL,
	is_recursos_naturais_5_comentario varchar NULL,
	is_recursos_naturais_5_proposta varchar NULL,
	is_recursos_naturais_6_resposta int4 NULL,
	is_recursos_naturais_6_comentario varchar NULL,
	is_recursos_naturais_6_proposta varchar NULL,
	is_recursos_naturais_7_resposta int4 NULL,
	is_recursos_naturais_7_comentario varchar NULL,
	is_recursos_naturais_7_proposta varchar NULL,
	is_recursos_naturais_8_resposta int4 NULL,
	is_recursos_naturais_8_comentario varchar NULL,
	is_recursos_naturais_8_proposta varchar NULL,
	is_agua_9_resposta int4 NULL,
	is_agua_9_comentario varchar NULL,
	is_agua_9_proposta varchar NULL,
	is_agua_10_resposta int4 NULL,
	is_agua_10_comentario varchar NULL,
	is_agua_10_proposta varchar NULL,
	is_conforto_ambiental_11_resposta int4 NULL,
	is_conforto_ambiental_11_comentario varchar NULL,
	is_conforto_ambiental_11_proposta varchar NULL,
	is_conforto_ambiental_12_resposta int4 NULL,
	is_conforto_ambiental_12_comentario varchar NULL,
	is_conforto_ambiental_12_proposta varchar NULL,
	is_conforto_ambiental_13_resposta int4 NULL,
	is_conforto_ambiental_13_comentario varchar NULL,
	is_conforto_ambiental_13_proposta varchar NULL,
	is_conforto_ambiental_14_resposta int4 NULL,
	is_conforto_ambiental_14_comentario varchar NULL,
	is_conforto_ambiental_14_proposta varchar NULL,
	is_residuos_15_resposta int4 NULL,
	is_residuos_15_comentario varchar NULL,
	is_residuos_15_proposta varchar NULL,
	is_residuos_16_resposta int4 NULL,
	is_residuos_16_comentario varchar NULL,
	is_residuos_16_proposta varchar NULL,
	is_residuos_17_resposta int4 NULL,
	is_residuos_17_comentario varchar NULL,
	is_residuos_17_proposta varchar NULL,
	is_residuos_18_resposta int4 NULL,
	is_residuos_18_comentario varchar NULL,
	is_residuos_18_proposta varchar NULL,
	is_eficiencia_energetica_1_resposta int4 NULL,
	is_eficiencia_energetica_1_comentario varchar NULL,
	is_eficiencia_energetica_1_proposta varchar NULL,
	is_eficiencia_energetica_2_resposta int4 NULL,
	is_eficiencia_energetica_2_comentario varchar NULL,
	is_eficiencia_energetica_2_proposta varchar NULL,
	is_eficiencia_energetica_3_resposta int4 NULL,
	is_eficiencia_energetica_3_comentario varchar NULL,
	is_eficiencia_energetica_3_proposta varchar NULL,
	is_eficiencia_energetica_4_resposta int4 NULL,
	is_eficiencia_energetica_4_comentario varchar NULL,
	is_eficiencia_energetica_4_proposta varchar NULL,
	meta_instance_id varchar NULL,
	meta_instance_name varchar NULL,
	removido bool DEFAULT false NULL,
	id_tecnico int4 NULL,
	caracteristicas_n_ingressaram_total_12_meses int4 NULL,
	caracteristicas_n_ingressaram_caf_12_meses int4 NULL,
	sim_nao_producao int4 NULL,
	sim_nao_file int4 NULL,
	sim_nao_pj int4 NULL,
	sim_nao_socio int4 NULL,
	obs varchar NULL,
	descricao varchar NULL,
	eixos_trabalhados varchar NULL,
	enfase int4 NULL,
	enfase_outros varchar NULL,
	metodologia varchar NULL,
	orientacoes varchar NULL,
	participantes_menos_10 int4 NULL,
	assinatura_rep_legal text NULL,
	_uri varchar(80) NULL,
	_creator_uri_user varchar(80) NULL,
	_creation_date timestamp NULL,
	_last_update_uri_user varchar(80) NULL,
	_last_update_date timestamp NULL,
	_model_version int4 NULL,
	_ui_version int4 NULL,
	_is_complete bool NULL,
	_submission_date timestamp NULL,
	_marked_as_complete_date timestamp NULL,
	complementado bool DEFAULT false NULL,
	validacao_status int4 DEFAULT 1 NULL,
	validacao_usuario int4 NULL,
	validacao_data timestamp NULL,
	validacao_obs text NULL,
	gf_contas_13_proposta varchar NULL,
	gc_comercial_21_comentario varchar NULL,
	gc_comercial_21_proposta varchar NULL,
	gc_comercial_21_resposta int4 NULL,
	gc_modelo_28_comentario varchar NULL,
	gc_modelo_28_proposta varchar NULL,
	gc_modelo_28_resposta int4 NULL,
	go_controle_26_comentario varchar NULL,
	go_controle_26_proposta varchar NULL,
	go_controle_26_resposta int4 NULL,
	go_controle_27_comentario varchar NULL,
	go_controle_27_proposta varchar NULL,
	go_controle_27_resposta int4 NULL,
	go_educacao_29_comentario varchar NULL,
	go_educacao_29_proposta varchar NULL,
	go_educacao_29_resposta int4 NULL,
	go_educacao_30_comentario varchar NULL,
	go_educacao_30_proposta varchar NULL,
	go_educacao_30_resposta int4 NULL,
	CONSTRAINT organizacao__uri_key UNIQUE (_uri),
	CONSTRAINT organizacao_pkey PRIMARY KEY (id),
	CONSTRAINT uk_organizacao_cnpj UNIQUE (cnpj),
	CONSTRAINT fk_validacao_usuario FOREIGN KEY (validacao_usuario) REFERENCES pinovara.users(id) ON DELETE SET NULL,
	CONSTRAINT organizacao_enfase_fkey FOREIGN KEY (enfase) REFERENCES pinovara_aux.enfase(id),
	CONSTRAINT organizacao_estado_fkey FOREIGN KEY (estado) REFERENCES pinovara_aux.estado(id),
	CONSTRAINT organizacao_gc_comercial_15_resposta_fkey FOREIGN KEY (gc_comercial_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_comercial_16_resposta_fkey FOREIGN KEY (gc_comercial_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_comercial_17_resposta_fkey FOREIGN KEY (gc_comercial_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_comercial_18_resposta_fkey FOREIGN KEY (gc_comercial_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_comercial_19_resposta_fkey FOREIGN KEY (gc_comercial_19_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_comercial_20_resposta_fkey FOREIGN KEY (gc_comercial_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_comercial_21_resposta_fkey FOREIGN KEY (gc_comercial_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_1_resposta_fkey FOREIGN KEY (gc_e_comercial_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_2_resposta_fkey FOREIGN KEY (gc_e_comercial_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_3_resposta_fkey FOREIGN KEY (gc_e_comercial_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_4_resposta_fkey FOREIGN KEY (gc_e_comercial_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_5_resposta_fkey FOREIGN KEY (gc_e_comercial_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_6_resposta_fkey FOREIGN KEY (gc_e_comercial_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_7_resposta_fkey FOREIGN KEY (gc_e_comercial_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_8_resposta_fkey FOREIGN KEY (gc_e_comercial_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_e_comercial_9_resposta_fkey FOREIGN KEY (gc_e_comercial_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_mercado_10_resposta_fkey FOREIGN KEY (gc_mercado_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_mercado_11_resposta_fkey FOREIGN KEY (gc_mercado_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_mercado_12_resposta_fkey FOREIGN KEY (gc_mercado_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_mercado_13_resposta_fkey FOREIGN KEY (gc_mercado_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_mercado_14_resposta_fkey FOREIGN KEY (gc_mercado_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_mercado_15_resposta_fkey FOREIGN KEY (gc_mercado_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_21_resposta_fkey FOREIGN KEY (gc_modelo_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_22_resposta_fkey FOREIGN KEY (gc_modelo_22_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_23_resposta_fkey FOREIGN KEY (gc_modelo_23_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_24_resposta_fkey FOREIGN KEY (gc_modelo_24_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_25_resposta_fkey FOREIGN KEY (gc_modelo_25_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_26_resposta_fkey FOREIGN KEY (gc_modelo_26_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_27_resposta_fkey FOREIGN KEY (gc_modelo_27_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gc_modelo_28_resposta_fkey FOREIGN KEY (gc_modelo_28_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_analise_22_resposta_fkey FOREIGN KEY (gf_analise_22_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_analise_23_resposta_fkey FOREIGN KEY (gf_analise_23_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_analise_24_resposta_fkey FOREIGN KEY (gf_analise_24_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_balanco_1_resposta_fkey FOREIGN KEY (gf_balanco_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_balanco_2_resposta_fkey FOREIGN KEY (gf_balanco_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_balanco_3_resposta_fkey FOREIGN KEY (gf_balanco_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_balanco_4_resposta_fkey FOREIGN KEY (gf_balanco_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_caixa_14_resposta_fkey FOREIGN KEY (gf_caixa_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_caixa_15_resposta_fkey FOREIGN KEY (gf_caixa_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_caixa_16_resposta_fkey FOREIGN KEY (gf_caixa_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_10_resposta_fkey FOREIGN KEY (gf_contas_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_11_resposta_fkey FOREIGN KEY (gf_contas_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_12_resposta_fkey FOREIGN KEY (gf_contas_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_13_resposta_fkey FOREIGN KEY (gf_contas_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_5_resposta_fkey FOREIGN KEY (gf_contas_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_6_resposta_fkey FOREIGN KEY (gf_contas_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_7_resposta_fkey FOREIGN KEY (gf_contas_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_8_resposta_fkey FOREIGN KEY (gf_contas_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_contas_9_resposta_fkey FOREIGN KEY (gf_contas_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_estoque_17_resposta_fkey FOREIGN KEY (gf_estoque_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_estoque_18_resposta_fkey FOREIGN KEY (gf_estoque_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_estoque_19_resposta_fkey FOREIGN KEY (gf_estoque_19_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_fiscal_25_resposta_fkey FOREIGN KEY (gf_fiscal_25_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_fiscal_26_resposta_fkey FOREIGN KEY (gf_fiscal_26_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_resultado_20_resposta_fkey FOREIGN KEY (gf_resultado_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gf_resultado_21_resposta_fkey FOREIGN KEY (gf_resultado_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_iic_1_resposta_fkey FOREIGN KEY (gi_iic_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_iic_2_resposta_fkey FOREIGN KEY (gi_iic_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_iic_3_resposta_fkey FOREIGN KEY (gi_iic_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_iic_4_resposta_fkey FOREIGN KEY (gi_iic_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_iic_5_resposta_fkey FOREIGN KEY (gi_iic_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_mar_6_resposta_fkey FOREIGN KEY (gi_mar_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_mar_7_resposta_fkey FOREIGN KEY (gi_mar_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_mar_8_resposta_fkey FOREIGN KEY (gi_mar_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_mar_9_resposta_fkey FOREIGN KEY (gi_mar_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_time_10_resposta_fkey FOREIGN KEY (gi_time_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_time_11_resposta_fkey FOREIGN KEY (gi_time_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_time_12_resposta_fkey FOREIGN KEY (gi_time_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_time_13_resposta_fkey FOREIGN KEY (gi_time_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gi_time_14_resposta_fkey FOREIGN KEY (gi_time_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_20_resposta_fkey FOREIGN KEY (go_controle_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_21_resposta_fkey FOREIGN KEY (go_controle_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_22_resposta_fkey FOREIGN KEY (go_controle_22_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_23_resposta_fkey FOREIGN KEY (go_controle_23_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_24_resposta_fkey FOREIGN KEY (go_controle_24_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_25_resposta_fkey FOREIGN KEY (go_controle_25_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_26_resposta_fkey FOREIGN KEY (go_controle_26_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_controle_27_resposta_fkey FOREIGN KEY (go_controle_27_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_14_resposta_fkey FOREIGN KEY (go_direcao_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_15_resposta_fkey FOREIGN KEY (go_direcao_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_16_resposta_fkey FOREIGN KEY (go_direcao_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_17_resposta_fkey FOREIGN KEY (go_direcao_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_18_resposta_fkey FOREIGN KEY (go_direcao_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_19_resposta_fkey FOREIGN KEY (go_direcao_19_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_20_resposta_fkey FOREIGN KEY (go_direcao_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_direcao_21_resposta_fkey FOREIGN KEY (go_direcao_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_educacao_26_resposta_fkey FOREIGN KEY (go_educacao_26_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_educacao_27_resposta_fkey FOREIGN KEY (go_educacao_27_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_educacao_28_resposta_fkey FOREIGN KEY (go_educacao_28_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_educacao_29_resposta_fkey FOREIGN KEY (go_educacao_29_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_educacao_30_resposta_fkey FOREIGN KEY (go_educacao_30_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_estrategia_5_resposta_fkey FOREIGN KEY (go_estrategia_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_estrategia_6_resposta_fkey FOREIGN KEY (go_estrategia_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_estrutura_1_resposta_fkey FOREIGN KEY (go_estrutura_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_estrutura_2_resposta_fkey FOREIGN KEY (go_estrutura_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_estrutura_3_resposta_fkey FOREIGN KEY (go_estrutura_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_estrutura_4_resposta_fkey FOREIGN KEY (go_estrutura_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_10_resposta_fkey FOREIGN KEY (go_organizacao_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_11_resposta_fkey FOREIGN KEY (go_organizacao_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_12_resposta_fkey FOREIGN KEY (go_organizacao_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_13_resposta_fkey FOREIGN KEY (go_organizacao_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_7_resposta_fkey FOREIGN KEY (go_organizacao_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_8_resposta_fkey FOREIGN KEY (go_organizacao_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_go_organizacao_9_resposta_fkey FOREIGN KEY (go_organizacao_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_geracao_18_resposta_fkey FOREIGN KEY (gp_geracao_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_geracao_19_resposta_fkey FOREIGN KEY (gp_geracao_19_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_geracao_20_resposta_fkey FOREIGN KEY (gp_geracao_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_desenvolvimento_10_resposta_fkey FOREIGN KEY (gp_p_desenvolvimento_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_desenvolvimento_11_resposta_fkey FOREIGN KEY (gp_p_desenvolvimento_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_desenvolvimento_12_resposta_fkey FOREIGN KEY (gp_p_desenvolvimento_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_desenvolvimento_13_resposta_fkey FOREIGN KEY (gp_p_desenvolvimento_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_1_resposta_fkey FOREIGN KEY (gp_p_organizacao_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_2_resposta_fkey FOREIGN KEY (gp_p_organizacao_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_3_resposta_fkey FOREIGN KEY (gp_p_organizacao_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_4_resposta_fkey FOREIGN KEY (gp_p_organizacao_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_5_resposta_fkey FOREIGN KEY (gp_p_organizacao_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_6_resposta_fkey FOREIGN KEY (gp_p_organizacao_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_7_resposta_fkey FOREIGN KEY (gp_p_organizacao_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_8_resposta_fkey FOREIGN KEY (gp_p_organizacao_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_p_organizacao_9_resposta_fkey FOREIGN KEY (gp_p_organizacao_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_trabalho_14_resposta_fkey FOREIGN KEY (gp_trabalho_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_trabalho_15_resposta_fkey FOREIGN KEY (gp_trabalho_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_trabalho_16_resposta_fkey FOREIGN KEY (gp_trabalho_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gp_trabalho_17_resposta_fkey FOREIGN KEY (gp_trabalho_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_16_resposta_fkey FOREIGN KEY (gpp_fluxo_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_17_resposta_fkey FOREIGN KEY (gpp_fluxo_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_18_resposta_fkey FOREIGN KEY (gpp_fluxo_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_19_resposta_fkey FOREIGN KEY (gpp_fluxo_19_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_20_resposta_fkey FOREIGN KEY (gpp_fluxo_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_21_resposta_fkey FOREIGN KEY (gpp_fluxo_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_fluxo_22_resposta_fkey FOREIGN KEY (gpp_fluxo_22_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_logistica_10_resposta_fkey FOREIGN KEY (gpp_logistica_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_logistica_11_resposta_fkey FOREIGN KEY (gpp_logistica_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_logistica_12_resposta_fkey FOREIGN KEY (gpp_logistica_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_logistica_7_resposta_fkey FOREIGN KEY (gpp_logistica_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_logistica_8_resposta_fkey FOREIGN KEY (gpp_logistica_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_logistica_9_resposta_fkey FOREIGN KEY (gpp_logistica_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_planejamento_4_resposta_fkey FOREIGN KEY (gpp_planejamento_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_planejamento_5_resposta_fkey FOREIGN KEY (gpp_planejamento_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_planejamento_6_resposta_fkey FOREIGN KEY (gpp_planejamento_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_producao_29_resposta_fkey FOREIGN KEY (gpp_producao_29_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_qualidade_23_resposta_fkey FOREIGN KEY (gpp_qualidade_23_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_qualidade_24_resposta_fkey FOREIGN KEY (gpp_qualidade_24_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_qualidade_25_resposta_fkey FOREIGN KEY (gpp_qualidade_25_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_qualidade_26_resposta_fkey FOREIGN KEY (gpp_qualidade_26_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_qualidade_27_resposta_fkey FOREIGN KEY (gpp_qualidade_27_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_qualidade_28_resposta_fkey FOREIGN KEY (gpp_qualidade_28_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_reg_sanitaria_1_resposta_fkey FOREIGN KEY (gpp_reg_sanitaria_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_reg_sanitaria_2_resposta_fkey FOREIGN KEY (gpp_reg_sanitaria_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_reg_sanitaria_3_resposta_fkey FOREIGN KEY (gpp_reg_sanitaria_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_valor_13_resposta_fkey FOREIGN KEY (gpp_valor_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_valor_14_resposta_fkey FOREIGN KEY (gpp_valor_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gpp_valor_15_resposta_fkey FOREIGN KEY (gpp_valor_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_ambiental_6_resposta_fkey FOREIGN KEY (gs_ambiental_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_ambiental_7_resposta_fkey FOREIGN KEY (gs_ambiental_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_ambiental_8_resposta_fkey FOREIGN KEY (gs_ambiental_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_ambiental_9_resposta_fkey FOREIGN KEY (gs_ambiental_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_15_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_16_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_17_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_18_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_19_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_19_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_20_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_20_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_21_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_21_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_impactos_ambiental_22_resposta_fkey FOREIGN KEY (gs_impactos_ambiental_22_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_reg_ambiental_10_resposta_fkey FOREIGN KEY (gs_reg_ambiental_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_reg_ambiental_11_resposta_fkey FOREIGN KEY (gs_reg_ambiental_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_reg_ambiental_12_resposta_fkey FOREIGN KEY (gs_reg_ambiental_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_reg_ambiental_13_resposta_fkey FOREIGN KEY (gs_reg_ambiental_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_reg_ambiental_14_resposta_fkey FOREIGN KEY (gs_reg_ambiental_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_socioambiental_1_resposta_fkey FOREIGN KEY (gs_socioambiental_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_socioambiental_2_resposta_fkey FOREIGN KEY (gs_socioambiental_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_socioambiental_3_resposta_fkey FOREIGN KEY (gs_socioambiental_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_socioambiental_4_resposta_fkey FOREIGN KEY (gs_socioambiental_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_gs_socioambiental_5_resposta_fkey FOREIGN KEY (gs_socioambiental_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_agua_10_resposta_fkey FOREIGN KEY (is_agua_10_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_agua_9_resposta_fkey FOREIGN KEY (is_agua_9_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_conforto_ambiental_11_resposta_fkey FOREIGN KEY (is_conforto_ambiental_11_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_conforto_ambiental_12_resposta_fkey FOREIGN KEY (is_conforto_ambiental_12_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_conforto_ambiental_13_resposta_fkey FOREIGN KEY (is_conforto_ambiental_13_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_conforto_ambiental_14_resposta_fkey FOREIGN KEY (is_conforto_ambiental_14_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_eficiencia_energetica_1_resposta_fkey FOREIGN KEY (is_eficiencia_energetica_1_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_eficiencia_energetica_2_resposta_fkey FOREIGN KEY (is_eficiencia_energetica_2_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_eficiencia_energetica_3_resposta_fkey FOREIGN KEY (is_eficiencia_energetica_3_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_eficiencia_energetica_4_resposta_fkey FOREIGN KEY (is_eficiencia_energetica_4_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_recursos_naturais_5_resposta_fkey FOREIGN KEY (is_recursos_naturais_5_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_recursos_naturais_6_resposta_fkey FOREIGN KEY (is_recursos_naturais_6_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_recursos_naturais_7_resposta_fkey FOREIGN KEY (is_recursos_naturais_7_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_recursos_naturais_8_resposta_fkey FOREIGN KEY (is_recursos_naturais_8_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_residuos_15_resposta_fkey FOREIGN KEY (is_residuos_15_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_residuos_16_resposta_fkey FOREIGN KEY (is_residuos_16_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_residuos_17_resposta_fkey FOREIGN KEY (is_residuos_17_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_is_residuos_18_resposta_fkey FOREIGN KEY (is_residuos_18_resposta) REFERENCES pinovara_aux.resposta(id),
	CONSTRAINT organizacao_municipio_fkey FOREIGN KEY (municipio) REFERENCES pinovara_aux.municipio_ibge(id),
	CONSTRAINT organizacao_participantes_menos_10_fkey FOREIGN KEY (participantes_menos_10) REFERENCES pinovara_aux.sim_nao(id),
	CONSTRAINT organizacao_representante_funcao_fkey FOREIGN KEY (representante_funcao) REFERENCES pinovara_aux.funcao(id),
	CONSTRAINT organizacao_sim_nao_file_fkey FOREIGN KEY (sim_nao_file) REFERENCES pinovara_aux.sim_nao(id),
	CONSTRAINT organizacao_sim_nao_pj_fkey FOREIGN KEY (sim_nao_pj) REFERENCES pinovara_aux.sim_nao(id),
	CONSTRAINT organizacao_sim_nao_producao_fkey FOREIGN KEY (sim_nao_producao) REFERENCES pinovara_aux.sim_nao(id),
	CONSTRAINT organizacao_sim_nao_socio_fkey FOREIGN KEY (sim_nao_socio) REFERENCES pinovara_aux.sim_nao(id)
);
CREATE INDEX idx_organizacao_validacao_status ON pinovara.organizacao USING btree (validacao_status);